import re
import os

def replace_in_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    for old, new in replacements:
        if old not in content:
            print(f"WARNING: String not found in {filepath}!")
            # print(old)
        else:
            content = content.replace(old, new)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Updated {filepath}")

en_replacements = [
(
"""[P086] September 22. - It is all over. Arthur has returned to his estate (Ring) with Quincey Morris. Quincey, what a wonderful man he is! I have no doubt that deep down in his heart, Quincey is mourning Lucy's death just as bitterly as we are. Yet he endured that sorrow silently, like a dignified Viking warrior. If America continues to raise such figures, it will undoubtedly stand tall as a truly formidable power before long. Professor Van Helsing is catching some sleep to prepare for his upcoming journey. He said he would leave for Amsterdam tonight and return tomorrow night. He added that he was merely going because he had a few supplies he needed to pack himself. He mentioned that he still had some business to take care of in London, so he might stay with me for the time being. Poor old professor! I am secretly worried that his iron-like stamina might have broken due to the extreme tension he suffered over the past week. I clearly saw his face as he forced down his boiling emotions throughout the funeral. After all the procedures were finished, we stood side by side next to Arthur. The poor young man Arthur spoke of the terrible surgery where he transfused his own blood into Lucy's veins. I watched Professor Van Helsing's face turn white as a sheet and then suddenly flush red and blue. Arthur confessed that after finishing the transfusion, he felt as if the two of them had truly become husband and wife, and he believed that in the eyes of God, she was undeniably his wife. Of course, none of us mentioned a word about the other transfusions she had received, and we will remain silent forever. After Arthur and Quincey left for the station, Van Helsing and I returned here. As soon as we were left alone in the carriage, surprisingly, the professor had a severe hysterical fit. Although he later insisted that it was not hysteria at all, and made excuses that a bizarrely absurd sense of humor had just been triggered amidst the terrible situation. He laughed uproariously until he was in tears, and I had to hurriedly lower the carriage blinds for fear that passersby might see and misunderstand. After bursting into laughter, he soon burst into tears, and like a weak woman, he repeated crying and laughing endlessly. I sternly scolded him as if dealing with a woman in such a state, but to no avail. At the moment when the nerves become weak to the point of breaking, the reactions of men and women are so different! Finally, when a solemn and serious look returned to his face, I asked him why he had laughed as if he had lost his mind, and why of all times such laughter had erupted in such a terrible moment. His answer was somewhat typical of him. It was logical, intense, and extremely bizarre. He said this.""",
"""[P086a] September 22. - It is all over. Arthur has returned to his estate (Ring) with Quincey Morris. Quincey, what a wonderful man he is! I have no doubt that deep down in his heart, Quincey is mourning Lucy's death just as bitterly as we are. Yet he endured that sorrow silently, like a dignified Viking warrior. If America continues to raise such figures, it will undoubtedly stand tall as a truly formidable power before long. Professor Van Helsing is catching some sleep to prepare for his upcoming journey. He said he would leave for Amsterdam tonight and return tomorrow night. He added that he was merely going because he had a few supplies he needed to pack himself. He mentioned that he still had some business to take care of in London, so he might stay with me for the time being. Poor old professor! I am secretly worried that his iron-like stamina might have broken due to the extreme tension he suffered over the past week. I clearly saw his face as he forced down his boiling emotions throughout the funeral. After all the procedures were finished, we stood side by side next to Arthur. The poor young man Arthur spoke of the terrible surgery where he transfused his own blood into Lucy's veins. I watched Professor Van Helsing's face turn white as a sheet and then suddenly flush red and blue. Arthur confessed that after finishing the transfusion, he felt as if the two of them had truly become husband and wife, and he believed that in the eyes of God, she was undeniably his wife. Of course, none of us mentioned a word about the other transfusions she had received, and we will remain silent forever.
[P086b] After Arthur and Quincey left for the station, Van Helsing and I returned here. As soon as we were left alone in the carriage, surprisingly, the professor had a severe hysterical fit. Although he later insisted that it was not hysteria at all, and made excuses that a bizarrely absurd sense of humor had just been triggered amidst the terrible situation. He laughed uproariously until he was in tears, and I had to hurriedly lower the carriage blinds for fear that passersby might see and misunderstand. After bursting into laughter, he soon burst into tears, and like a weak woman, he repeated crying and laughing endlessly. I sternly scolded him as if dealing with a woman in such a state, but to no avail. At the moment when the nerves become weak to the point of breaking, the reactions of men and women are so different! Finally, when a solemn and serious look returned to his face, I asked him why he had laughed as if he had lost his mind, and why of all times such laughter had erupted in such a terrible moment. His answer was somewhat typical of him. It was logical, intense, and extremely bizarre. He said this."""
),
(
"""[P087a] "Ah, you do not understand at all, my friend John. Just because I laughed pointlessly does not mean I am not sad. Look, didn't I cry my eyes out even when the bizarre laughter was choking me. But conversely, when I am wailing, I am not entirely just sad either. Because even in that terrible moment, laughter inevitably comes. Keep in mind that a laugh which knocks politely and asks 'May I come in?' is never a real laugh. No! King Laugh is absolute and omnipotent, deciding entirely on his own when and how to come. He asks no one for permission and chooses no particular time. He simply declares 'I have arrived!'. Now look, for example, right now my heart is tearing apart with sorrow in the face of the death of a girl who was so lovely. Although I am old and tired, I devoted my blood, my time, my medical skills, and even my sweet sleep without regret to save her. I poured everything into her, even abandoning my other patients. Yet I ended up bursting into laughter right beside her grave. At the very devastating moment when the clods of dirt falling from the worker's shovel poured thud, thud onto her coffin and drained the color from my face. When I think of the poor boy Arthur, my heart weeps tears of blood. If I had been blessed by heaven and my son had lived, he would surely be exactly that age. Because of that lovely child who even had the same hair and eye color. Now, you can probably guess why I feel so affectionately toward that young man. But the moment he confessed an unbearable, terrible secret as a husband that dug into my heart, and so the very moment my paternal love leaned toward him so fiercely that it would not turn to any other man—not even to you, John, since we are closer to equal comrades in arms than father and son—'King Laugh' suddenly came, roaring into my ear 'I have come! I have arrived!'. Until my veins throbbed again and he brought the sunlight he held to my pale cheeks. Oh, friend John. The world is a truly bizarre place. It is a grey world stained with misery, sorrow, and hardship. However, when 'King Laugh' arrives, he makes all that sorrow and pain dance to the tune he plays. A bleeding heart, dry bones tumbling in a graveyard, and even the hot tears flowing down cheeks—all begin to dance in unison to the bizarre music he blows from lips entirely devoid of a smile. And trust me, friend John. His sudden arrival is in a way fortunate and something to be thankful for. We humans are like a rope pulled taut from both sides. And then when tears burst forth, like rain soaking the rope, those tears tighten us until we cannot move. If we aren't careful, the rope might snap under the tension. But at that time, 'King Laugh' arrives like warm sunlight and loosens the taut tension. Thanks to that, we do not collapse and can move forward carrying our respective heavy burdens."
[P087b] I did not want to hurt him by pretending not to understand his thoughts and picking a fight. But because I simply could not comprehend the reason he had laughed like a madman, I ended up asking anyway. The face he returned had a much more solemn look, and his voice had also changed completely.""",
"""[P087a] "Ah, you do not understand at all, my friend John. Just because I laughed pointlessly does not mean I am not sad. Look, didn't I cry my eyes out even when the bizarre laughter was choking me. But conversely, when I am wailing, I am not entirely just sad either. Because even in that terrible moment, laughter inevitably comes. Keep in mind that a laugh which knocks politely and asks 'May I come in?' is never a real laugh. No! King Laugh is absolute and omnipotent, deciding entirely on his own when and how to come. He asks no one for permission and chooses no particular time. He simply declares 'I have arrived!'. Now look, for example, right now my heart is tearing apart with sorrow in the face of the death of a girl who was so lovely. Although I am old and tired, I devoted my blood, my time, my medical skills, and even my sweet sleep without regret to save her. I poured everything into her, even abandoning my other patients. Yet I ended up bursting into laughter right beside her grave. At the very devastating moment when the clods of dirt falling from the worker's shovel poured thud, thud onto her coffin and drained the color from my face.
[P087b] When I think of the poor boy Arthur, my heart weeps tears of blood. If I had been blessed by heaven and my son had lived, he would surely be exactly that age. Because of that lovely child who even had the same hair and eye color. Now, you can probably guess why I feel so affectionately toward that young man. But the moment he confessed an unbearable, terrible secret as a husband that dug into my heart, and so the very moment my paternal love leaned toward him so fiercely that it would not turn to any other man—not even to you, John, since we are closer to equal comrades in arms than father and son—'King Laugh' suddenly came, roaring into my ear 'I have come! I have arrived!'. Until my veins throbbed again and he brought the sunlight he held to my pale cheeks. Oh, friend John. The world is a truly bizarre place. It is a grey world stained with misery, sorrow, and hardship. However, when 'King Laugh' arrives, he makes all that sorrow and pain dance to the tune he plays. A bleeding heart, dry bones tumbling in a graveyard, and even the hot tears flowing down cheeks—all begin to dance in unison to the bizarre music he blows from lips entirely devoid of a smile. And trust me, friend John. His sudden arrival is in a way fortunate and something to be thankful for. We humans are like a rope pulled taut from both sides. And then when tears burst forth, like rain soaking the rope, those tears tighten us until we cannot move. If we aren't careful, the rope might snap under the tension. But at that time, 'King Laugh' arrives like warm sunlight and loosens the taut tension. Thanks to that, we do not collapse and can move forward carrying our respective heavy burdens."
[P087c] I did not want to hurt him by pretending not to understand his thoughts and picking a fight. But because I simply could not comprehend the reason he had laughed like a madman, I ended up asking anyway. The face he returned had a much more solemn look, and his voice had also changed completely."""
),
(
"""[P103] Lately, the Hampstead area has been plagued by a bizarre series of disappearances. Gossips whisper that these incidents bear an uncanny resemblance to the so-called 'Kensington Horror,' the 'Woman with the Knife,' and the 'Woman in Black' cases that caused an uproar in the past. In just two or three days, there have been successive incidents of young children wandering lost from home or vanishing without a trace while playing on the Heath. The missing children were all too young to coherently explain the terrible situations that befell them. However, if you carefully pick apart the children's gibberish, one chilling commonality is found: they were with a 'bloofer (beautiful) lady'. The children always vanished in the late evening when twilight settled, and two of them were found the next early morning in a cold state. Because the first child to go missing stated, "A beautiful lady coaxed me to go for a walk and I followed her," the local people assume that the other children simply overheard that plausible excuse and are mimicking it exactly. Considering that a game of deceiving each other with brazen lies is currently in full swing among the little ones, such adult speculation is not unreasonable. According to a message sent by our correspondent, the sight of muddy little brats scrambling over one another to play-act as the 'beautiful lady' is quite ridiculous. He added that if our newspaper's satirical cartoonists saw the scene firsthand, they could capture a bizarre irony within the dizzying gap between reality and imagination. The fact that the 'beautiful lady' has undeniably emerged as a popular role in the kids' impromptu outdoor plays might just be due to the shallow human nature of following trends. The correspondent joked aimlessly that seeing the dirt-covered kids acting alluringly with their wild imaginations, not even the greatest actress of our time, Ellen Terry, could pull off such a cute and charming performance.""",
"""[P103a] Lately, the Hampstead area has been plagued by a bizarre series of disappearances. Gossips whisper that these incidents bear an uncanny resemblance to the so-called 'Kensington Horror,' the 'Woman with the Knife,' and the 'Woman in Black' cases that caused an uproar in the past. In just two or three days, there have been successive incidents of young children wandering lost from home or vanishing without a trace while playing on the Heath. The missing children were all too young to coherently explain the terrible situations that befell them. However, if you carefully pick apart the children's gibberish, one chilling commonality is found: they were with a 'bloofer (beautiful) lady'. The children always vanished in the late evening when twilight settled, and two of them were found the next early morning in a cold state.
[P103b] Because the first child to go missing stated, "A beautiful lady coaxed me to go for a walk and I followed her," the local people assume that the other children simply overheard that plausible excuse and are mimicking it exactly. Considering that a game of deceiving each other with brazen lies is currently in full swing among the little ones, such adult speculation is not unreasonable. According to a message sent by our correspondent, the sight of muddy little brats scrambling over one another to play-act as the 'beautiful lady' is quite ridiculous. He added that if our newspaper's satirical cartoonists saw the scene firsthand, they could capture a bizarre irony within the dizzying gap between reality and imagination. The fact that the 'beautiful lady' has undeniably emerged as a popular role in the kids' impromptu outdoor plays might just be due to the shallow human nature of following trends. The correspondent joked aimlessly that seeing the dirt-covered kids acting alluringly with their wild imaginations, not even the greatest actress of our time, Ellen Terry, could pull off such a cute and charming performance."""
)
]

ko_replacements = [
(
"""[P086] 9월 22일. - 모든 것이 끝났다. 아서는 친구 퀸시 모리스와 함께 영지(Ring)로 돌아갔다. 퀸시, 참으로 멋진 사나이가 아닌가! 나는 퀸시가 마음속 깊은 곳에서는 우리 못지않게 비통하게 루시의 죽음을 슬퍼하고 있다고 믿어 의심치 않는다. 하지만 그는 마치 위엄 있는 바이킹 전사처럼 그 슬픔을 묵묵히 견뎌냈다. 만약 미국이 앞으로도 그런 인물들을 계속 배출해낸다면, 멀지 않은 미래에 진정으로 위협적인 강대국으로 우뚝 설 것이 분명하다. 반 헬싱 교수는 다가올 여정을 대비해 잠을 청하는 중이다. 그는 오늘 밤 암스테르담으로 떠났다가 내일 밤에 돌아올 것이라고 했다. 직접 챙겨야 할 몇 가지 물품이 있어 다녀오는 것뿐이라고 덧붙였다. 런던에서 아직 처리할 일이 남아 있기 때문에, 당분간은 나와 함께 지낼 수도 있다고 했다. 가여운 노교수님! 나는 지난 일주일 동안 겪은 극도의 긴장감 때문에 그의 강철 같은 체력이 무너져 내린 것은 아닐까 내심 걱정스럽다. 장례식 내내 끓어오르는 감정을 억누르던 그의 얼굴을 나는 똑똑히 보았다. 모든 절차가 끝난 후, 우리는 아서 옆에 나란히 섰다. 불쌍한 청년 아서는 자신의 피를 루시의 정맥에 수혈했던 그 끔찍한 수술에 대해 이야기했다. 나는 반 헬싱 교수의 얼굴이 백지장처럼 창백해졌다가 갑자기 울그락불그락해지는 것을 지켜보았다. 아서는 수혈을 마친 후 두 사람이 진정으로 부부가 된 것 같았으며, 신의 눈에도 그녀가 변함없는 자신의 아내일 것이라 믿는다고 고백했다. 물론 우리 중 누구도 그녀가 받았던 다른 수혈에 대해서는 한마디도 꺼내지 않았고, 영원히 침묵할 것이다. 아서와 퀸시가 역으로 떠난 후, 반 헬싱과 나는 이곳으로 돌아왔다. 마차 안에 단둘이 남겨지자마자, 놀랍게도 교수는 심한 히스테리 발작을 일으켰다. 비록 나중에는 그것이 전혀 히스테리가 아니었다고 우기며, 끔찍한 상황 속에서 그저 기괴할 정도로 터무니없는 유머 감각이 발동했을 뿐이라고 변명했지만 말이다. 그는 눈물이 날 정도로 배를 잡고 웃어댔고, 나는 행인들이 보고 오해할까 봐 서둘러 마차 블라인드를 내려야 했다. 웃음을 터뜨리던 그는 곧바로 눈물을 쏟아냈고, 마치 나약한 여인처럼 울고 웃기를 끝없이 반복했다. 나는 그런 상태의 여인을 다루듯 단호하게 그를 꾸짖었지만, 아무 소용이 없었다. 신경이 끊어질 듯 약해진 순간, 남자와 여자의 반응이 이토록 다르다니! 마침내 그의 얼굴에 엄숙하고 진지한 표정이 돌아왔을 때, 나는 왜 정신을 놓은 사람처럼 웃어댔는지, 그리고 하필 왜 그 끔찍한 순간에 그런 웃음이 터져 나왔는지 물었다. 그의 대답은 다소 그다운 것이었다. 논리적이고, 강렬하며, 극도로 기괴했다. 그는 이렇게 말했다.""",
"""[P086a] 9월 22일. - 모든 것이 끝났다. 아서는 친구 퀸시 모리스와 함께 영지(Ring)로 돌아갔다. 퀸시, 참으로 멋진 사나이가 아닌가! 나는 퀸시가 마음속 깊은 곳에서는 우리 못지않게 비통하게 루시의 죽음을 슬퍼하고 있다고 믿어 의심치 않는다. 하지만 그는 마치 위엄 있는 바이킹 전사처럼 그 슬픔을 묵묵히 견뎌냈다. 만약 미국이 앞으로도 그런 인물들을 계속 배출해낸다면, 멀지 않은 미래에 진정으로 위협적인 강대국으로 우뚝 설 것이 분명하다. 반 헬싱 교수는 다가올 여정을 대비해 잠을 청하는 중이다. 그는 오늘 밤 암스테르담으로 떠났다가 내일 밤에 돌아올 것이라고 했다. 직접 챙겨야 할 몇 가지 물품이 있어 다녀오는 것뿐이라고 덧붙였다. 런던에서 아직 처리할 일이 남아 있기 때문에, 당분간은 나와 함께 지낼 수도 있다고 했다. 가여운 노교수님! 나는 지난 일주일 동안 겪은 극도의 긴장감 때문에 그의 강철 같은 체력이 무너져 내린 것은 아닐까 내심 걱정스럽다. 장례식 내내 끓어오르는 감정을 억누르던 그의 얼굴을 나는 똑똑히 보았다. 모든 절차가 끝난 후, 우리는 아서 옆에 나란히 섰다. 불쌍한 청년 아서는 자신의 피를 루시의 정맥에 수혈했던 그 끔찍한 수술에 대해 이야기했다. 나는 반 헬싱 교수의 얼굴이 백지장처럼 창백해졌다가 갑자기 울그락불그락해지는 것을 지켜보았다. 아서는 수혈을 마친 후 두 사람이 진정으로 부부가 된 것 같았으며, 신의 눈에도 그녀가 변함없는 자신의 아내일 것이라 믿는다고 고백했다. 물론 우리 중 누구도 그녀가 받았던 다른 수혈에 대해서는 한마디도 꺼내지 않았고, 영원히 침묵할 것이다.
[P086b] 아서와 퀸시가 역으로 떠난 후, 반 헬싱과 나는 이곳으로 돌아왔다. 마차 안에 단둘이 남겨지자마자, 놀랍게도 교수는 심한 히스테리 발작을 일으켰다. 비록 나중에는 그것이 전혀 히스테리가 아니었다고 우기며, 끔찍한 상황 속에서 그저 기괴할 정도로 터무니없는 유머 감각이 발동했을 뿐이라고 변명했지만 말이다. 그는 눈물이 날 정도로 배를 잡고 웃어댔고, 나는 행인들이 보고 오해할까 봐 서둘러 마차 블라인드를 내려야 했다. 웃음을 터뜨리던 그는 곧바로 눈물을 쏟아냈고, 마치 나약한 여인처럼 울고 웃기를 끝없이 반복했다. 나는 그런 상태의 여인을 다루듯 단호하게 그를 꾸짖었지만, 아무 소용이 없었다. 신경이 끊어질 듯 약해진 순간, 남자와 여자의 반응이 이토록 다르다니! 마침내 그의 얼굴에 엄숙하고 진지한 표정이 돌아왔을 때, 나는 왜 정신을 놓은 사람처럼 웃어댔는지, 그리고 하필 왜 그 끔찍한 순간에 그런 웃음이 터져 나왔는지 물었다. 그의 대답은 다소 그다운 것이었다. 논리적이고, 강렬하며, 극도로 기괴했다. 그는 이렇게 말했다."""
),
(
"""[P087a] "아, 자네는 내 마음을 너무나도 모르는군, 내 친구 존. 내가 실없이 웃어댔다고 해서 슬프지 않은 것은 아니라네. 보게나, 기괴한 웃음이 목을 조를 때조차 나는 펑펑 울지 않았나. 하지만 반대로 내가 통곡할 때도, 온전히 슬프기만 한 것은 아니라네. 그 끔찍한 순간에도 웃음은 어김없이 찾아오거든. 예의 바르게 노크를 하며 '들어가도 될까요?' 하고 묻는 웃음은 결코 진짜 웃음이 아니라는 것을 명심하게. 아니지! '웃음 대왕'은 절대적이고 전능해서, 언제 어떻게 올지 전적으로 자기 혼자서 결정한다네. 그는 누구에게도 허락을 구하지 않고, 특정한 때를 고르지도 않지. 그저 '내가 왔다!'라고 당당히 선언할 뿐이야. 자 보게나, 예를 들어 바로 지금 내 가슴은 그토록 사랑스러웠던 한 소녀의 죽음 앞에서 슬픔으로 갈기갈기 찢어지고 있다네. 나는 비록 늙고 지쳤지만, 그녀를 살리기 위해 내 피와, 내 시간과, 내 의술과, 심지어 달콤한 잠조차 후회 없이 바쳤어. 내 다른 환자들마저 저버린 채, 그녀에게 모든 것을 쏟아부었지. 그런데도 나는 결국 그녀의 무덤 바로 옆에서 웃음을 터뜨리고 말았다네. 일꾼의 삽에서 떨어지는 흙덩이가 쿵, 쿵 소리를 내며 그녀의 관 위로 쏟아져 내려 내 얼굴을 하얗게 질리게 만들던 바로 그 처참한 순간에 말이야. 불쌍한 소년 아서를 생각하면, 내 가슴은 피눈물을 흘린다네. 만약 내가 하늘의 축복을 받아 내 아들이 살아있었다면, 분명 딱 그 나이였을 테니까. 머리카락과 눈동자 색깔마저 똑같았던 그 사랑스러운 아이 말일세. 이제 내가 왜 그 청년에게 그토록 애정을 느끼는지 짐작할 수 있을 거야. 하지만 그가 남편으로서 가슴을 파고드는 참을 수 없이 끔찍한 비밀을 고백하던 그 순간, 그래서 나의 부성애가 다른 어떤 남자에게도—자네와 나는 부자지간이라기보다는 동등한 전우에 더 가까우니 자네에게조차도—향하지 않을 만큼 맹렬하게 그에게 쏠리던 바로 그 순간, '웃음 대왕'이 갑자기 찾아와 내 귓가에 '내가 왔다! 내가 도착했다!'라고 표효했지. 내 핏줄이 다시 요동치고 그가 품고 온 햇살을 내 창백한 뺨에 가져다줄 때까지 말이야. 오, 친구 존. 세상은 참으로 기괴한 곳이라네. 비참함과 슬픔, 고난으로 얼룩진 잿빛 세상이지. 하지만 '웃음 대왕'이 찾아오면, 그는 그 모든 슬픔과 고통을 자신이 연주하는 곡조에 맞춰 춤추게 만든다네. 피 흘리는 가슴, 묘지에서 뒹구는 마른 뼈, 그리고 뺨을 타고 흐르는 뜨거운 눈물까지도—모두 미소라고는 전혀 없는 입술로 그가 불어대는 기괴한 음악에 맞춰 일제히 춤을 추기 시작하지. 그리고 날 믿게나, 친구 존. 그의 갑작스러운 방문은 어떤 면에서는 다행스럽고 감사해야 할 일이라네. 우리 인간은 양쪽에서 팽팽하게 잡아당기는 밧줄과도 같아. 그러다 밧줄을 적시는 비처럼 눈물이 터져 나오면, 그 눈물은 우리가 꼼짝도 할 수 없을 만큼 우리를 단단히 조여온다네. 자칫하면 그 팽팽한 긴장감에 밧줄이 끊어질지도 모르지. 하지만 그때 '웃음 대왕'이 따뜻한 햇살처럼 찾아와 그 팽팽한 긴장감을 느슨하게 풀어준다네. 덕분에 우리는 쓰러지지 않고 각자의 무거운 짐을 짊어진 채 앞으로 나아갈 수 있는 거야."
[P087b] 나는 그의 생각을 이해하지 못하는 척하며 시비를 걸어 그에게 상처를 주고 싶지 않았다. 하지만 왜 그가 미치광이처럼 웃어댔는지 도저히 그 이유를 납득할 수 없었기에, 결국 묻고 말았다. 돌아온 그의 얼굴은 훨씬 더 엄숙한 표정이었고, 목소리 또한 완전히 달라져 있었다.""",
"""[P087a] "아, 자네는 내 마음을 너무나도 모르는군, 내 친구 존. 내가 실없이 웃어댔다고 해서 슬프지 않은 것은 아니라네. 보게나, 기괴한 웃음이 목을 조를 때조차 나는 펑펑 울지 않았나. 하지만 반대로 내가 통곡할 때도, 온전히 슬프기만 한 것은 아니라네. 그 끔찍한 순간에도 웃음은 어김없이 찾아오거든. 예의 바르게 노크를 하며 '들어가도 될까요?' 하고 묻는 웃음은 결코 진짜 웃음이 아니라는 것을 명심하게. 아니지! '웃음 대왕'은 절대적이고 전능해서, 언제 어떻게 올지 전적으로 자기 혼자서 결정한다네. 그는 누구에게도 허락을 구하지 않고, 특정한 때를 고르지도 않지. 그저 '내가 왔다!'라고 당당히 선언할 뿐이야. 자 보게나, 예를 들어 바로 지금 내 가슴은 그토록 사랑스러웠던 한 소녀의 죽음 앞에서 슬픔으로 갈기갈기 찢어지고 있다네. 나는 비록 늙고 지쳤지만, 그녀를 살리기 위해 내 피와, 내 시간과, 내 의술과, 심지어 달콤한 잠조차 후회 없이 바쳤어. 내 다른 환자들마저 저버린 채, 그녀에게 모든 것을 쏟아부었지. 그런데도 나는 결국 그녀의 무덤 바로 옆에서 웃음을 터뜨리고 말았다네. 일꾼의 삽에서 떨어지는 흙덩이가 쿵, 쿵 소리를 내며 그녀의 관 위로 쏟아져 내려 내 얼굴을 하얗게 질리게 만들던 바로 그 처참한 순간에 말이야.
[P087b] 불쌍한 소년 아서를 생각하면, 내 가슴은 피눈물을 흘린다네. 만약 내가 하늘의 축복을 받아 내 아들이 살아있었다면, 분명 딱 그 나이였을 테니까. 머리카락과 눈동자 색깔마저 똑같았던 그 사랑스러운 아이 말일세. 이제 내가 왜 그 청년에게 그토록 애정을 느끼는지 짐작할 수 있을 거야. 하지만 그가 남편으로서 가슴을 파고드는 참을 수 없이 끔찍한 비밀을 고백하던 그 순간, 그래서 나의 부성애가 다른 어떤 남자에게도—자네와 나는 부자지간이라기보다는 동등한 전우에 더 가까우니 자네에게조차도—향하지 않을 만큼 맹렬하게 그에게 쏠리던 바로 그 순간, '웃음 대왕'이 갑자기 찾아와 내 귓가에 '내가 왔다! 내가 도착했다!'라고 표효했지. 내 핏줄이 다시 요동치고 그가 품고 온 햇살을 내 창백한 뺨에 가져다줄 때까지 말이야. 오, 친구 존. 세상은 참으로 기괴한 곳이라네. 비참함과 슬픔, 고난으로 얼룩진 잿빛 세상이지. 하지만 '웃음 대왕'이 찾아오면, 그는 그 모든 슬픔과 고통을 자신이 연주하는 곡조에 맞춰 춤추게 만든다네. 피 흘리는 가슴, 묘지에서 뒹구는 마른 뼈, 그리고 뺨을 타고 흐르는 뜨거운 눈물까지도—모두 미소라고는 전혀 없는 입술로 그가 불어대는 기괴한 음악에 맞춰 일제히 춤을 추기 시작하지. 그리고 날 믿게나, 친구 존. 그의 갑작스러운 방문은 어떤 면에서는 다행스럽고 감사해야 할 일이라네. 우리 인간은 양쪽에서 팽팽하게 잡아당기는 밧줄과도 같아. 그러다 밧줄을 적시는 비처럼 눈물이 터져 나오면, 그 눈물은 우리가 꼼짝도 할 수 없을 만큼 우리를 단단히 조여온다네. 자칫하면 그 팽팽한 긴장감에 밧줄이 끊어질지도 모르지. 하지만 그때 '웃음 대왕'이 따뜻한 햇살처럼 찾아와 그 팽팽한 긴장감을 느슨하게 풀어준다네. 덕분에 우리는 쓰러지지 않고 각자의 무거운 짐을 짊어진 채 앞으로 나아갈 수 있는 거야."
[P087c] 나는 그의 생각을 이해하지 못하는 척하며 시비를 걸어 그에게 상처를 주고 싶지 않았다. 하지만 왜 그가 미치광이처럼 웃어댔는지 도저히 그 이유를 납득할 수 없었기에, 결국 묻고 말았다. 돌아온 그의 얼굴은 훨씬 더 엄숙한 표정이었고, 목소리 또한 완전히 달라져 있었다."""
),
(
"""[P103] 최근 햄프스테드 지역에 기괴한 연쇄 실종 사건이 발생하고 있다. 호사가들은 이 사건들이 과거 세간을 떠들썩하게 했던 이른바 '켄싱턴 공포', '칼을 든 여인', '검은 옷의 여인' 사건과 섬뜩할 정도로 비슷하다고 수군거린다. 불과 2, 3일 사이에 어린아이들이 집을 나와 길을 잃거나 히스(Heath)에서 놀다가 흔적도 없이 사라지는 사건이 연이어 발생한 것이다. 실종된 아이들은 자신들에게 닥친 끔찍한 상황을 조리 있게 설명하기에는 너무 어렸다. 하지만 아이들의 횡설수설을 주의 깊게 분석해 보면 한 가지 소름 끼치는 공통점이 발견되는데, 바로 '아름다운(bloofer) 여인'과 함께 있었다는 것이다. 아이들은 항상 땅거미가 질 무렵인 늦은 저녁에 사라졌고, 그중 두 명은 다음 날 이른 아침에 싸늘해진 상태로 발견되었다. 첫 번째로 실종되었던 아이가 "아름다운 여인이 같이 산책하자고 꼬드겨서 따라갔어요"라고 진술한 탓에, 지역 사람들은 다른 아이들이 그 그럴듯한 변명을 엿듣고 똑같이 흉내 내는 것이라고 짐작하고 있다. 현재 어린아이들 사이에서 천연덕스러운 거짓말로 서로를 속이는 놀이가 한창 유행하고 있다는 점을 고려하면, 어른들의 그런 추측이 아주 터무니없는 것은 아니다. 본지 통신원이 보낸 메시지에 따르면, 흙투성이 꼬마 녀석들이 서로 '아름다운 여인' 역을 맡겠다며 아등바등 다투는 모습이 꽤나 우스꽝스럽다고 한다. 그는 만약 우리 신문사의 풍자 만화가들이 그 광경을 직접 본다면, 현실과 상상 사이의 아찔한 괴리감 속에서 기괴한 아이러니를 포착해 낼 수 있을 것이라고 덧붙였다. '아름다운 여인'이 아이들의 즉석 야외 연극에서 의심할 여지 없이 인기 있는 배역으로 떠오른 것은 그저 유행을 좇는 얄팍한 인간 본성 때문일지도 모른다. 통신원은 흙투성이 아이들이 풍부한 상상력을 발휘해 매혹적으로 연기하는 모습을 보면, 우리 시대 최고의 여배우 엘런 테리(Ellen Terry)라 할지라도 그렇게 귀엽고 깜찍한 연기는 해내지 못할 것이라며 실없는 농담을 던졌다.""",
"""[P103a] 최근 햄프스테드 지역에 기괴한 연쇄 실종 사건이 발생하고 있다. 호사가들은 이 사건들이 과거 세간을 떠들썩하게 했던 이른바 '켄싱턴 공포', '칼을 든 여인', '검은 옷의 여인' 사건과 섬뜩할 정도로 비슷하다고 수군거린다. 불과 2, 3일 사이에 어린아이들이 집을 나와 길을 잃거나 히스(Heath)에서 놀다가 흔적도 없이 사라지는 사건이 연이어 발생한 것이다. 실종된 아이들은 자신들에게 닥친 끔찍한 상황을 조리 있게 설명하기에는 너무 어렸다. 하지만 아이들의 횡설수설을 주의 깊게 분석해 보면 한 가지 소름 끼치는 공통점이 발견되는데, 바로 '아름다운(bloofer) 여인'과 함께 있었다는 것이다. 아이들은 항상 땅거미가 질 무렵인 늦은 저녁에 사라졌고, 그중 두 명은 다음 날 이른 아침에 싸늘해진 상태로 발견되었다.
[P103b] 첫 번째로 실종되었던 아이가 "아름다운 여인이 같이 산책하자고 꼬드겨서 따라갔어요"라고 진술한 탓에, 지역 사람들은 다른 아이들이 그 그럴듯한 변명을 엿듣고 똑같이 흉내 내는 것이라고 짐작하고 있다. 현재 어린아이들 사이에서 천연덕스러운 거짓말로 서로를 속이는 놀이가 한창 유행하고 있다는 점을 고려하면, 어른들의 그런 추측이 아주 터무니없는 것은 아니다. 본지 통신원이 보낸 메시지에 따르면, 흙투성이 꼬마 녀석들이 서로 '아름다운 여인' 역을 맡겠다며 아등바등 다투는 모습이 꽤나 우스꽝스럽다고 한다. 그는 만약 우리 신문사의 풍자 만화가들이 그 광경을 직접 본다면, 현실과 상상 사이의 아찔한 괴리감 속에서 기괴한 아이러니를 포착해 낼 수 있을 것이라고 덧붙였다. '아름다운 여인'이 아이들의 즉석 야외 연극에서 의심할 여지 없이 인기 있는 배역으로 떠오른 것은 그저 유행을 좇는 얄팍한 인간 본성 때문일지도 모른다. 통신원은 흙투성이 아이들이 풍부한 상상력을 발휘해 매혹적으로 연기하는 모습을 보면, 우리 시대 최고의 여배우 엘런 테리(Ellen Terry)라 할지라도 그렇게 귀엽고 깜찍한 연기는 해내지 못할 것이라며 실없는 농담을 던졌다."""
)
]

en_file = "C:/git_repo/TKprof_book/books/dracula/chapters/ch13_en.txt"
ko_file = "C:/git_repo/TKprof_book/books/dracula/chapters/ch13_ko.txt"

replace_in_file(en_file, en_replacements)
replace_in_file(ko_file, ko_replacements)
