import codecs

paras = [
'''"Oh, yes, I know. I read the last two letters you sent." I continued.''',
'''"I think that incident was a huge shock to Jonathan. When he went to town last Thursday, he had another episode."''',
'''"An episode? So soon after recovering from brain fever! That is not a good sign. What kind of episode was it?"''',
'''"He believed he saw someone who reminded him of something truly terrifying—the very cause that gave him brain fever in the first place." At that moment, a flood of emotions overwhelmed me all at once. Pity for Jonathan, the terrible fear he had experienced, the horrifying mysteries written in his journal, and the dread that had weighed heavily on my mind ever since—all of this crashed over me like a giant wave. I must have lost my reason. I fell to my knees, reaching out my hands to him, begging him to please make my husband well again. He took my hands, gently helped me up, and seated me on the sofa. Then he sat beside me, held my hand tightly, and spoke in an incredibly kind voice.''',
'''"My life is dry and lonely. Buried in work, I have not had much time for friendship. But since my friend John Seward called me here, I have met many truly wonderful people and witnessed their nobility. As I grow older, the loneliness of my life feels even greater. So please believe me when I say that I approached you with deep respect. You have given me hope—perhaps not hope for the matter I am investigating, but hope that there are still wonderful women left in this world who make life happy. Women with a life and truth that will serve as a great example to children in the future. I am so glad that I can be of some small help to you. If your husband is suffering, that is the very field I have studied and experienced my entire life. I promise you, I will gladly help him with all my power. I will make his life strong and sturdy again, and bring happiness back to your life. Now, please eat first. You are exhausted and overwhelmed with anxiety. Mr. Jonathan would not want to see your pale face, either. It is not good for him to see the person he loves sad. So, for his sake, you must eat and smile. You have already told me everything about Lucy, so I won't bring it up for a while so as not to cause you pain. I plan to stay in Exeter tonight. I need to carefully think over the things you have told me. After giving it enough thought, with your permission, I will ask you a few questions. Then, please tell me everything you know about your husband Jonathan's condition—but not now. First, eat, and then you can tell me everything."''',
'''When we returned to the living room after lunch, he said.''',
'''"Now, please tell me everything about him." When the moment came to speak to such a learned and excellent man, I was suddenly seized with fear that he might think of me as a weak fool and Jonathan as a madman—because the contents of that journal were so bizarre. I hesitated, unable to open my mouth. But he was so kind and gentle, and he promised to help me. I trusted him and began to speak.''',
'''"Dr. Van Helsing, even if what I am about to tell you sounds extremely strange, please do not laugh at me or my husband. Since yesterday, I have been suffering from a deep doubt, as if I had caught a fever. Please take pity on me, and do not think me foolish for half-believing these bizarre stories." He reassured me with a warm voice and tone.''',
'''"Oh, Madam, if you knew how strange the matter I am currently investigating is, you would rather laugh at me. I have learned that no matter how bizarre a story may seem, one should not lightly dismiss another's belief. I have always tried to keep an open mind. What closes a person's mind is not ordinary daily life, but strange and bizarre things—things that make you doubt your own sanity."''',
'''"Thank you, I want to thank you a thousand times! You have lifted a heavy burden from my heart. If you will allow it, I would like to give you a document to read, Doctor. It is quite long, but I typed it out for you. This will explain the suffering Jonathan and I have gone through. This is a copy of a journal meticulously recording everything that happened while he was abroad. I dare not add a single word to its contents. Please read it yourself and judge. And the next time we meet, I hope you will share your thoughts with me."''',
'''He promised as he took the papers. "I promise. If you permit me, I will come to see you and your husband as early as possible tomorrow morning."''',
'''"Jonathan will be back at 11:30. Come then, have lunch with us, and say hello to Jonathan. Then, if you catch the 3:34 PM express train, you can arrive at Paddington Station before 8 o'clock." He seemed very surprised as I recited the train schedule perfectly. He didn't know that I had memorized all the train schedules to and from Exeter to help Jonathan whenever he had to leave in a hurry.''',
'''So he left with the papers, and I am sitting here now lost in thought—not even knowing what I am thinking about.''',
'''* * * * *''',
'''Letter from Van Helsing to Mrs. Harker (delivered by messenger).''',
'''"September 25, 6:00 PM.''',
'''"Dear Madam Mina,—''',
'''"I have read all of your husband's astonishing journal. You may sleep peacefully tonight without a single doubt. No matter how bizarre and terrifying the contents of that journal may be, all of it is true! I can guarantee it with my life. It might be a disaster for others, but you and your husband have nothing to fear. Your husband is a truly brave and noble man. I tell you this based on my experience of meeting countless people: a man who could climb down that castle wall and enter that room—and do it twice, no less—is a man who will never be permanently broken by any shock. Your husband's brain and heart are perfectly healthy. I can swear this confidently even before meeting him in person. So please rest assured. I have many questions to ask your husband later. Meeting you today is a tremendous blessing for me. My head is spinning from learning so much all at once—more dizzy than ever before. I too need time to think.''',
'''"Sincerely,''',
'''"Abraham Van Helsing."'''
]

with codecs.open('C:/git_repo/TKprof_book/books/dracula/chapters/ch14_en.txt', 'a', 'utf-8') as f:
    f.write('\n\n'.join(paras) + '\n\n')
