import codecs

paras = [
'''Chapter 14''',
'''Mina Harker's Journal''',
'''September 23.—Jonathan is much better after a restless night. I am glad he has so much work to do, for it distracts him from those terrible memories. I am also truly happy that he is free from the pressure of his new partnership. I always believed he would not lose himself, and I am so proud of how perfectly my Jonathan handles his new duties, which befit his promotion. He said he couldn't come home for lunch today, so he will be working late. Since I have finished all the housework, I plan to lock myself in my room and read the journal he wrote in Transylvania....''',
'''September 24.—I could not bring myself to write last night. Jonathan's terrifying account shook me too deeply. My poor, precious husband! Whether all of it was real or mere illusion, I cannot even begin to imagine how much he must have suffered. Is there even a hint of truth in that story? Did he suffer from such extreme stress that he caught a fever and wrote down those horrifying delusions, or did those things actually happen? I may never know, because I do not have the courage to ask him directly.... But who on earth was that man we ran into yesterday! Jonathan was absolutely certain it was him.... Poor man! Perhaps Mr. Hawkins's funeral upset him so much that his past trauma resurfaced.... He believes all of it is entirely true. I remember what he told me on our wedding day. "Whether sleeping or waking, whether mad or sane, unless a solemn duty calls me back to that painful time." There seems to be a consistent thread in all of this.... That the terrible Count was coming to London.... If that is true, and if he arrived in London with a multitude of followers.... Then perhaps there is a solemn duty waiting for us. If that moment comes, we must never run away.... I will make preparations. I should bring the typewriter at once and copy his journal. That way, others can read it if needed. And if such a thing happens, making these preparations might prevent poor Jonathan from suffering another shock. I will explain the situation on his behalf and ensure he is never tormented or worried again. Someday, if Jonathan fully recovers from his nervous breakdown, he might want to confide in me. When that time comes, I can ask questions, properly understand what happened, and then think about how to comfort him.''',
'''Letter from Van Helsing to Mrs. Harker.''',
'''"September 24.''',
'''(Private)''',
'''"Dear Madam,—''',
'''"Please forgive me for writing to you so unexpectedly, using the sad news of Miss Lucy Westenra's passing as an excuse to reach out. Thanks to Lord Godalming's consideration, I was able to read Miss Lucy's letters and papers. This is because I am currently deeply involved in a very important and serious matter. During this process, I discovered the letters you sent, and I learned how special your friendship was and how much you cared for Miss Lucy. Oh, Madam Mina, I earnestly beg you in the name of that love. Please help me. This is for the sake of others. It is to correct a terrible wrong and to alleviate suffering far worse than you can imagine. Could I possibly meet with you in person? You can trust me. I am a friend of Dr. John Seward and Lord Godalming (Lucy's Arthur). For the time being, we must keep this matter a secret from everyone. If you would permit me to know when and where I can meet you, I will rush to Exeter immediately. Madam, I sincerely apologize. Reading your letters to poor Lucy, I know how kind you are and how much you are suffering due to your husband's illness. Therefore, I implore you to keep this matter a secret from your husband, as it might cause him harm. I seek your deepest forgiveness once again.''',
'''"Yours sincerely, Van Helsing."''',
'''Telegram from Mrs. Harker to Van Helsing.''',
'''"September 25.—If you can catch the 10:15 train today, please do so. I can meet you anytime after you arrive.''',
'''"Wilhelmina Harker."''',
'''Mina Harker's Journal.''',
'''September 25.—I am very excited about Dr. Van Helsing's upcoming visit. Perhaps it is because of the expectation that he might provide a clue to the terrible things Jonathan went through. Moreover, since he cared for our poor Lucy until she passed away, I am sure he will tell me about her in detail. He must be coming because of Lucy's sleepwalking, not because of Jonathan's matter. Does that mean the real truth of what happened to Jonathan will remain forever unknown! I am so foolish. The contents of that terrifying journal have completely captured my imagination, painting everything in dark colors. Of course, he is coming about Lucy. Lucy's sleepwalking returned, and she must have fallen ill because of that dreadful night on the cliff. I was so absorbed in my own affairs that I completely forgot how ill Lucy had been since then. Lucy must have told the doctor about her sleepwalking incident on the cliff and that I knew all about it. So now, the doctor wants to hear what I know to better understand Lucy's symptoms. I hope keeping it a secret from Mrs. Westenra was the right choice. If my silence harmed poor Lucy in any way, I would never forgive myself. I hope Dr. Van Helsing does not blame me. With so many difficult and anxious things lately, I do not have the energy to handle any more.''',
'''Sometimes, a good cry seems to clear the mind, just like the sky after a rain. It is probably because reading Jonathan's journal yesterday upset me, and Jonathan left early this morning for the whole day. It is the first time we have been apart since we got married. I just hope my precious husband stays safe and that nothing happens to upset him. It is already 2 o'clock. The doctor will be here soon. I should not mention Jonathan's journal until he asks first. I am so glad I typed out my journal. If the doctor asks about Lucy, I can just hand this over to him. It will save a lot of trouble answering every single question.''',
'''* * * * *''',
'''Later.—He came and went. Oh, what a strange encounter! My head is spinning! It feels like a dream. Could all of this, or even just a little bit of it, be true? If I hadn't read Jonathan's journal first, I wouldn't have believed it at all. Poor, so poor our Jonathan! How much terrible suffering he must have endured. Please, God, do not let this haunt him again. I will do my best to protect him too, but perhaps it might bring him greater comfort and help. Even if the result is something terrible and frightening, knowing for certain that his eyes, ears, and reason were not deceived, but that everything was real, might be better. Perhaps what torments him the most is his own self-doubt. If that doubt disappears, if it is revealed that what he experienced was not an illusion but reality, he might be able to gather his courage and prepare to overcome the shock. Seeing that Arthur and Dr. Seward brought Dr. Van Helsing all the way from distant Holland to care for Lucy, he must be a highly skilled and excellent person. Meeting him in person, I felt his kind, good, and noble character. When he comes again tomorrow, I must ask him about Jonathan. God willing, all this sorrow and anxiety might lead to a good conclusion. I once wanted to practice doing interviews. Jonathan's friend at the 'Exeter News' told me that memory is everything in an interview, and even if it's refined later, every single word of the conversation must be recorded exactly. Since this was a rare opportunity, I will try to record today's conversation without leaving out a single word.''',
'''The clock pointed to half past two when there was a knock. I gathered my courage and waited. A few minutes later, Mary opened the door and announced, "Dr. Van Helsing is here."''',
'''As I stood up to greet him, he approached. He was of medium height and sturdy build, with broad shoulders above a wide, deep chest. His neck was thick and firmly supported a well-balanced head. Just by looking at him holding his head high, I could immediately feel deep thought and strong power. His broad, large head behind his ears exuded a noble dignity. His cleanly shaven face featured a strong, angular jaw, a resolute and expressive large mouth, and an appropriately large, straight nose. The sensitive nostrils of his nose seemed to widen whenever he closed his mouth tightly and furrowed his thick eyebrows. His broad, straight forehead stretched straight up before tilting back over two prominent ridges. Thanks to that forehead, his reddish hair naturally fell to the sides and back without covering his brow. His large, dark blue eyes, set wide apart, seemed capable of changing from gentle to stern depending on his mood. He said to me.'''
]

with codecs.open('C:/git_repo/TKprof_book/books/dracula/chapters/ch14_en.txt', 'w', 'utf-8') as f:
    f.write('\n\n'.join(paras) + '\n\n')
