import os

ko_content_1 = """1: 제26장 (Chapter 26)
2: 수어드 박사의 일기 (Dr. Seward's Diary)
3: 10월 29일.—이 글은 바르나(Varna)에서 갈라츠(Galatz)로 가는 기차 안에서 적고 있습니다. 어젯밤 해질 무렵에 우리 모두는 조금 일찍 모였습니다. 각자 맡은 바 최선을 다했고, 우리가 할 수 있는 한 갈라츠에 도착했을 때의 모든 여정과 작업에 대한 준비를 마쳤습니다. 평소의 최면 시간이 다가오자 하커 부인(미나)은 최면 상태에 들어갈 준비를 했습니다. 반 헬싱 교수가 평소보다 훨씬 길고 진지하게 최면을 유도한 끝에 부인은 최면 상태에 빠졌습니다. 보통은 힌트만 주어도 그녀가 말을 시작하지만, 이번에는 교수가 단호하게 여러 번 질문을 던진 후에야 비로소 무언가를 알아낼 수 있었습니다. 마침내 그녀의 대답이 들려왔습니다.
4: "아무것도 보이지 않습니다. 우리는 정지해 있습니다. 찰랑거리는 물결은 없고, 그저 굵은 밧줄(계류삭)에 물이 부드럽게 부딪혀 소용돌이치는 소리만 일정하게 들립니다. 멀고 가까운 곳에서 사람들의 목소리가 들리고, 노젓는 소리와 노걸이가 삐걱거리는 소리가 들립니다. 어딘가에서 총소리가 나고, 그 메아리가 아주 멀리서 들려옵니다. 머리 위로는 발소리가 쿵쿵거리고, 밧줄과 쇠사슬이 끌리는 소리가 납니다. 이게 뭐죠? 한 줄기 빛이 스며들고, 공기가 제게 불어오는 것이 느껴집니다."
5: 여기서 그녀는 멈추었습니다. 소파에 누워 있던 그녀는 충동적으로 일어나더니, 무거운 것을 들어올리는 것처럼 양손을 손바닥이 위로 향하게 들어올렸습니다. 반 헬싱과 나는 서로를 이해한다는 듯이 쳐다보았습니다. 퀸시는 눈썹을 살짝 치켜올리며 그녀를 유심히 쳐다보았고, 조나단 하커는 본능적으로 자신의 쿠크리(구르카 족의 단검) 자루를 꽉 쥐었습니다. 긴 침묵이 흘렀습니다. 우리 모두는 그녀가 말할 수 있는 시간이 지나가고 있다는 것을 알고 있었지만, 아무 말도 소용없을 것이라고 느꼈습니다. 갑자기 그녀가 똑바로 앉더니, 눈을 뜨며 다정하게 말했습니다.
6: "다들 차 한 잔 하시겠어요? 모두 많이 피곤하실 텐데요!" 우리는 그녀를 기쁘게 해주는 것 외에는 도리가 없어 그렇게 하겠다고 했습니다. 그녀가 차를 준비하러 서둘러 나간 후, 반 헬싱이 말했습니다.
7: "보셨지요, 친구들. 드라큘라 백작이 육지에 가까워졌습니다. 그는 이미 그의 흙 상자에서 벗어났습니다. 하지만 아직 육지에 오르지는 못했습니다. 밤 동안 어딘가에 숨어 있을지도 모르지만, 만약 육지로 옮겨지지 않거나 배가 육지에 닿지 않는다면 그는 땅을 밟을 수 없습니다. 그런 경우 밤이라면 변신해서 휘트비(Whitby)에서처럼 육지로 뛰어내리거나 날아갈 수 있습니다. 하지만 그가 육지에 오르기 전에 날이 밝는다면 누군가 그를 옮겨주지 않는 한 탈출할 수 없습니다. 그리고 만약 누군가 그를 옮긴다면 세관원들이 상자 안의 내용물을 발견할 수 있습니다. 즉, 오늘 밤이나 동트기 전에 그가 육지로 도망치지 못한다면 하루 전체를 허비하게 될 것입니다. 그러면 우리가 제시간에 도착할 수 있습니다. 밤에 도망치지 못한다면 우리는 낮에 꼼짝 못 하고 상자에 갇힌 그를 덮칠 수 있기 때문입니다. 낮에는 발각될까 두려워 깨어 있는 본래의 모습으로 돌아갈 수 없으니까요."
8: 더 이상 할 말이 없었기에 우리는 인내심을 가지고 동틀 녘까지 기다렸습니다. 그때쯤이면 하커 부인으로부터 더 많은 것을 알아낼 수 있을 테니까요.
9: 오늘 이른 아침, 우리는 숨을 죽인 채 최면 상태에 빠진 그녀의 대답을 초조하게 기다렸습니다. 최면 상태로 들어가는 데 평소보다 더 오랜 시간이 걸렸고, 그녀가 입을 열었을 때는 해가 완전히 뜨기까지 남은 시간이 너무 짧아 우리는 절망하기 시작했습니다. 반 헬싱은 혼신의 힘을 다해 최면을 시도하는 듯했고, 마침내 그의 의지에 따라 그녀가 대답했습니다.
10: "사방이 어둡습니다. 제 위치와 같은 높이에서 물이 찰랑거리는 소리가 들리고, 나무와 나무가 마찰하며 삐걱거리는 소리가 납니다." 그녀가 말을 멈추자, 붉은 해가 솟아올랐습니다. 우리는 오늘 밤까지 기다려야만 합니다.
11: 그래서 우리는 애타는 기다림 속에서 갈라츠를 향해 여행하고 있습니다. 새벽 2시에서 3시 사이에 도착할 예정이었지만, 이미 부쿠레슈티(Bucharest)에서 3시간이나 연착되어 해가 중천에 뜬 후에야 도착할 수 있을 것 같습니다. 따라서 그 사이 하커 부인을 통해 두 번 더 최면 메시지를 받을 수 있으며, 두 메시지 중 하나라도 지금 벌어지고 있는 일에 대해 중요한 단서를 줄 수 있을 것입니다.
12: *       *       *       *       *
13: 나중에.—해가 지고 또 졌습니다. 다행히 기차가 역에 서지 않을 때 해가 져서 방해를 받지 않았습니다. 역에 정차해 있었다면 필요한 고요함과 고립된 환경을 확보하지 못했을 것입니다. 하커 부인은 오늘 아침보다도 더 최면에 걸리기 어려워했습니다. 우리가 가장 필요로 하는 이 순간에, 백작의 감각을 읽어내는 그녀의 능력이 사라져버릴까 두렵습니다. 그녀의 상상력이 개입하기 시작한 것 같습니다. 지금까지는 최면 상태에서 오직 단순한 사실에만 집중했지만, 이런 현상이 계속된다면 결국 우리를 오도할 수 있습니다. 백작이 그녀를 지배하는 힘도 그녀의 투시력과 함께 사라진다면 다행이겠지만, 그렇지 않을까 봐 두렵습니다. 마침내 그녀가 입을 열었을 때, 그녀의 말은 수수께끼 같았습니다.
14: "무언가 밖으로 나가고 있습니다. 차가운 바람처럼 저를 스쳐 지나가는 것이 느껴집니다. 멀리서 혼란스러운 소리가 들립니다. 사람들이 낯선 언어로 떠드는 소리, 거칠게 떨어지는 물소리, 그리고 늑대들의 울음소리 같은 것이 들립니다." 그녀는 말을 멈췄고, 몇 초 동안 점점 더 심하게 몸을 떨더니 마침내 중풍에 걸린 것처럼 격렬하게 몸을 떨었습니다. 교수가 다급하게 질문을 퍼부었음에도 그녀는 더 이상 아무 말도 하지 않았습니다. 최면에서 깨어났을 때 그녀는 춥고 지치고 기운이 없었지만, 정신만은 매우 맑았습니다. 그녀는 자신이 한 말을 전혀 기억하지 못했고, 무슨 말을 했는지 우리에게 물었습니다. 우리가 그 내용을 알려주자 그녀는 한참 동안 말없이 깊은 생각에 잠겼습니다.
15: *       *       *       *       *
"""

ko_content_2 = """16: 10월 30일, 오전 7시.—이제 우리는 갈라츠에 거의 도착했습니다. 나중에는 글을 쓸 시간이 없을지도 모르겠습니다. 오늘 아침, 우리 모두는 초조하게 일출을 기다렸습니다. 반 헬싱 교수는 최면 상태로 들어가는 것이 점점 어려워진다는 것을 알고 평소보다 일찍 손짓(passes)을 시작했습니다. 그러나 정해진 시간이 될 때까지 아무런 효과가 없었고, 해가 뜨기 불과 1분 전에야 그녀는 평소보다 훨씬 더 힘겹게 최면에 빠져들었습니다. 교수는 지체 없이 질문을 던졌고, 그녀도 재빠르게 대답했습니다.
17: "사방이 어둡습니다. 제 귀 높이에서 물이 소용돌이치며 흘러가는 소리가 들리고, 나무와 나무가 마찰하며 삐걱거리는 소리가 납니다. 멀리서 소들의 울음소리가 들립니다. 또 다른 소리, 이상한 소리가 들리는데 마치——" 그녀는 말을 멈추더니 얼굴이 하얗게, 점점 더 창백해졌습니다.
18: "계속해요, 계속! 말하라고 명령합니다!" 반 헬싱이 애타는 목소리로 말했습니다. 동시에 그의 눈에는 절망감이 서려 있었습니다. 떠오른 태양이 하커 부인의 창백한 얼굴까지 붉게 물들이고 있었기 때문입니다. 그녀가 눈을 떴고, 무척이나 상냥하고 아무렇지도 않은 듯 말하는 그녀의 모습에 우리 모두는 깜짝 놀랐습니다.
19: "아, 교수님. 제가 할 수 없다는 걸 아시면서 왜 그런 부탁을 하시나요? 저는 아무것도 기억나지 않습니다." 그러고는 우리 얼굴에 떠오른 놀라움을 본 그녀가 곤혹스러운 표정으로 우리를 번갈아 보며 말했습니다.
20: "제가 무슨 말을 했나요? 무슨 짓을 했죠? 저는 아무것도 모릅니다. 그저 반쯤 잠든 채 누워 있다가 '계속해요! 말하라고 명령합니다!'라고 하시는 말씀만 들었어요. 저를 마치 나쁜 아이인 것처럼 이래라저래라 명령하시는 게 너무 우스웠어요!"
21: "아, 미나 부인." 그가 슬프게 말했습니다. "만약 증명이 필요하다면, 이것이야말로 제가 부인을 얼마나 사랑하고 존경하는지 보여주는 증거입니다. 제가 기쁜 마음으로 복종하는 분에게 명령을 내리다니요! 부인을 위한 그 간절한 한마디가 그토록 이상하게 들렸다니 말입니다."
22: 기적 소리가 울리고 있습니다. 갈라츠에 가까워지고 있습니다. 우리는 불안과 조바심으로 속이 타들어 가고 있습니다.
23: 미나 하커의 일기 (Mina Harker's Journal)
24: 10월 30일.—모리스 씨가 전보로 미리 예약해둔 호텔로 저를 데려갔습니다. 그는 외국어를 전혀 하지 못해 우리 중 가장 시간 여유가 있었기 때문입니다. 일행은 바르나에서와 거의 비슷하게 역할을 분담했습니다. 다만 우리의 일정이 극도로 촉박했기에, 고달밍 경은 관리들에게 자신의 지위가 신원 보증 역할을 해줄 것을 기대하고 부영사를 찾아갔습니다. 조나단과 두 의사 선생님은 '차리나 캐서린(Czarina Catherine)' 호의 입항에 관한 자세한 내용을 알아보기 위해 선박 대리점으로 갔습니다.
25: *       *       *       *       *
26: 나중에.—고달밍 경이 돌아왔습니다. 영사는 자리를 비웠고 부영사는 병이 나서, 한 서기가 일상적인 업무를 처리하고 있었다고 합니다. 그는 매우 친절했고, 자신이 할 수 있는 일이라면 무엇이든 돕겠다고 제안했습니다.
27: 조나단 하커의 일기 (Jonathan Harker's Journal)
28: 10월 30일.—9시 정각에 반 헬싱 박사, 수어드 박사, 그리고 나는 런던 해프굿(Hapgood) 상회의 대리점인 매켄지 앤 스타인코프(Mackenzie & Steinkoff) 사를 방문했습니다. 그들은 고달밍 경의 전보 요청에 대한 응답으로 런던으로부터 우리에게 가능한 모든 편의를 제공하라는 전보를 미리 받아두고 있었습니다. 그들은 무척 친절하고 정중했으며, 강 항구에 정박해 있던 차리나 캐서린 호에 우리를 곧바로 데려갔습니다. 그곳에서 도넬슨(Donelson)이라는 선장을 만나 항해에 관한 이야기를 들었습니다. 그는 평생 이렇게 순조로운 항해는 처음이었다고 말했습니다.
29: "이보쇼!" 그가 말했습니다. "오히려 겁이 날 지경이었소. 균형을 맞추려고 나중에 뭔가 끔찍한 불운을 겪게 될까 봐 말이오. 런던에서 흑해까지, 마치 악마가 자기 목적을 위해 돛에 바람을 불어넣어 주는 것처럼 내내 순풍을 타고 달리는 건 뭔가 으스스한 일이지 않소. 게다가 항해 내내 아무것도 볼 수가 없었소. 배나 항구, 혹은 곶(headland)에 가까워질 때마다 짙은 안개가 우리를 덮쳐서는 함께 이동했으니 말이오. 안개가 걷힌 뒤에 밖을 내다봐도 아무것도 보이지 않았소. 지브롤터(Gibraltar)를 지날 때는 신호조차 보낼 수 없었고, 다르다넬스(Dardanelles) 해협에 도착해 통과 허가증을 기다려야 할 때까지 그 어떤 배와도 마주치지 않았소. 처음에는 안개가 걷힐 때까지 돛을 접고 주변을 서성일까 생각도 했지만, 이내 악마가 우리를 흑해로 빨리 밀어넣으려 작정했다면 우리가 원하든 원치 않든 그렇게 할 거란 생각이 들었소. 빨리 도착하면 선주들 눈 밖에 날 일도 없고 무역에 해가 될 것도 없으니, 목적을 달성한 그 늙은 악마(Old Mon)가 우리 앞길을 막지 않은 것에 적당히 감사할 일이었소." 단순함과 교활함, 미신과 상업적인 타산이 뒤섞인 이 말에 반 헬싱이 자극을 받아 말했습니다.
30: "내 친구여, 그 악마는 사람들이 생각하는 것보다 훨씬 교활합니다. 그리고 그는 자신이 상대를 제대로 만났다는 것을 알고 있지요!" 선장은 이 칭찬에 나쁘지 않은 기색을 보이며 말을 이었습니다.
31: "보스포루스(Bosphorus) 해협을 지나자 선원들이 투덜거리기 시작했소. 루마니아 출신 선원 몇 명이 찾아와서는, 런던에서 출발하기 직전에 기이하게 생긴 노인이 실어둔 큰 상자를 바다에 던져버리자고 하더군. 난 선원들이 그 사내를 뚫어지게 보면서, 사악한 눈길(evil eye)을 피하려 두 손가락을 뻗는 걸 봤었소. 이보쇼! 외국 놈들의 미신이란 참으로 우스꽝스럽기 짝이 없소! 난 당장 그놈들을 자기 자리로 돌려보냈지만, 그 직후 안개가 짙어지자 나 역시 그 큰 상자 때문이라고 말하진 않겠지만 뭔가 꺼림칙한 기분이 들긴 했소. 어쨌든 우리는 계속 나아갔고, 5일 동안 안개가 걷히지 않기에 바람이 이끄는 대로 놔두었소. 악마가 어딘가로 가길 원한다면 어차피 알아서 도착할 테니까 말이오. 아니라면 뭐, 우리가 알아서 잘 살피면 될 일이었소. 아니나 다를까, 줄곧 바다도 순탄했고 수심도 깊었소. 그리고 이틀 전 아침, 안개 사이로 태양이 비치자 우리는 갈라츠 맞은편 강에 도착해 있었소. 루마니아 놈들은 미쳐 날뛰며 옳든 그르든 그 상자를 꺼내 강에 던져버리라고 난리였지. 난 쇠지레를 들고 녀석들과 승강이를 벌여야 했소. 마지막 놈이 머리를 감싸 쥐고 갑판에서 일어났을 때야 비로소, 나는 사악한 눈길이든 뭐든 선주들의 재산과 신용은 다뉴브강에 처박히는 것보다 내 손에 있는 게 더 낫다는 걸 녀석들에게 납득시켰소. 명심하시오, 녀석들은 상자를 강에 던지려고 이미 갑판에 꺼내둔 상태였소. 상자에 '바르나 경유 갈라츠행(Galatz via Varna)'이라고 적혀 있길래, 항구에 짐을 내릴 때까지 그대로 두고 아예 치워버리자 생각했지. 그날은 하역 작업을 많이 못 해서 밤새 정박해 있어야 했지만, 아침 일찍 해 뜨기 한 시간 전에, 어떤 사내가 영국에서 온 주문서를 들고 승선했소. '드라큘라 백작(Count Dracula)'이라고 적힌 상자를 인수하러 왔더군. 아니나 다를까 그건 마침 갑판에 딱 꺼내져 있었으니 일이 쉽게 풀린 셈이지. 사내의 서류는 완벽했고, 나 역시 그 망할 상자를 치워버리게 되어 기뻤소. 나조차 그 상자가 점점 불안해지던 참이었으니까. 만약 배에 악마의 짐이 실려 있었다면, 틀림없이 그 상자였을 거요!"
32: "상자를 가져간 사내의 이름이 무엇입니까?" 반 헬싱 박사가 애써 흥분을 가라앉히며 물었습니다.
33: "금방 알려드리리다!" 그는 대답하더니, 자기 선실로 내려가 '임마누엘 힐데스하임(Immanuel Hildesheim)'이라고 서명된 영수증을 가져왔습니다. 주소는 부르겐슈트라세(Burgen-strasse) 16번지였습니다. 선장이 아는 것은 이것이 전부였으므로 우리는 감사를 표하고 그곳을 떠났습니다.
34: 우리는 사무실에서 힐데스하임을 만났습니다. 그는 양 같은 코에 페즈(터키 모자)를 쓴 아델피 극장(Adelphi Theatre, 과장된 연극이 열리던 런던 극장) 풍의 유대인이었습니다. 그의 주장은 현금 보상(specie)에 맞춰져 있었고(우리가 구두점처럼 돈을 꺼내 주어야 했습니다), 약간의 흥정 끝에 자신이 아는 바를 털어놓았습니다. 내용은 단순했지만 중요했습니다. 그는 런던의 드 빌(de Ville) 씨로부터 갈라츠에 차리나 캐서린 호 편으로 상자 하나가 도착할 테니, 세관을 피할 수 있게 해 뜨기 전에 인수하라는 편지를 받았다고 합니다. 그리고 그 상자를 강 하류에서 항구까지 무역을 하는 슬로바키아인(Slovaks)들과 거래하는 페트로프 스킨스키(Petrof Skinsky)라는 자에게 넘기라는 지시를 받았다는 것입니다. 일의 대가로는 영국 은행권(지폐)을 받았고, 이는 다뉴브 국제 은행에서 금화로 정당하게 환전했습니다. 스킨스키가 찾아왔을 때, 그는 운반비를 아끼려고 그를 배로 데려가 상자를 직접 넘겼다고 합니다. 그것이 그가 아는 전부였습니다.
35: 우리는 스킨스키를 찾아 나섰지만 그를 찾을 수 없었습니다. 그에게 별로 호감이 없어 보이는 한 이웃은, 그가 이틀 전에 어디론가 떠났고 행선지는 아무도 모른다고 했습니다. 이는 집주인의 말을 통해서도 확인되었습니다. 집주인은 어젯밤 10시에서 11시 사이에 심부름꾼을 통해 영국 돈으로 된 밀린 월세와 집 열쇠를 받았다고 했습니다. 우리는 다시 벽에 부딪혔습니다.
36: 우리가 이야기를 나누고 있을 때 누군가 달려와 헐떡이며 성 베드로(St. Peter) 교회 묘지 담장 안에서 스킨스키의 시신이 발견되었는데, 야생 동물에게 물어뜯긴 것처럼 목이 찢겨 있었다고 말했습니다. 우리와 이야기하던 사람들은 그 끔찍한 광경을 보러 달려갔고, 여자들은 "이건 슬로바키아 놈의 짓이야!"라고 소리쳤습니다. 우리는 어쩌다 이 사건에 연루되어 지체될까 두려워 서둘러 그곳을 떠났습니다.
37: 숙소로 돌아오는 길에 우리는 어떤 확실한 결론에도 도달할 수 없었습니다. 상자가 물길을 따라 어딘가로 이동 중이라는 것은 확신했지만, 그곳이 어디인지는 우리가 알아내야만 했습니다. 우리는 무거운 마음을 안고 미나가 있는 호텔로 돌아왔습니다.
38: 우리가 모였을 때 가장 먼저 논의한 것은 미나를 다시 우리의 계획에 포함시킬지 여부였습니다. 상황이 절망적으로 치닫고 있었고, 비록 위험하긴 하지만 적어도 하나의 가능성이 될 수 있었기 때문입니다. 첫 번째 단계로, 나는 그녀에게 했던 약속(비밀을 지키겠다는 약속)에서 풀려났습니다.
39: 미나 하커의 일기.
40: 10월 30일 저녁.—그들은 너무 지치고 기진맥진하고 낙담한 상태라 휴식을 취하기 전에는 아무것도 할 수 없었습니다. 그래서 저는 제가 그동안의 모든 일을 기록할 테니 30분만이라도 누워 쉬라고 모두에게 부탁했습니다. "여행자용(Traveller's)" 타자기를 발명한 사람과 제게 이것을 구해준 모리스 씨에게 너무나 감사합니다. 펜으로 글을 써야 했다면 정말 막막했을 거예요....
41: 기록을 다 마쳤습니다. 불쌍하고 소중한 내 사랑 조나단, 그가 얼마나 고통받았을지, 지금은 또 얼마나 고통받고 있을지. 그는 거의 숨도 쉬지 않는 것처럼 소파에 누워 있고, 온몸이 무너져 내린 것 같습니다. 미간은 찌푸려져 있고 얼굴은 고통으로 일그러져 있습니다. 가엾은 사람, 어쩌면 생각을 하고 있는지도 모르겠습니다. 생각에 집중하느라 얼굴에 온통 주름이 진 것을 볼 수 있으니까요. 아! 제가 조금이라도 도울 수 있다면 좋으련만.... 제가 할 수 있는 일을 해야겠습니다.
42: 반 헬싱 박사님께 부탁드려서 아직 보지 못했던 모든 서류를 건네받았습니다.... 그들이 쉬는 동안 저는 모든 자료를 주의 깊게 살펴볼 것이고, 어쩌면 어떤 결론에 도달할 수 있을지도 모릅니다. 교수님의 본보기를 따라 내 앞에 놓인 사실들을 편견 없이 생각해 봐야겠습니다....
43: *       *       *       *       *
44: 하나님의 섭리 덕분에 제가 무언가를 발견해 낸 것 같습니다. 지도를 가져와서 살펴봐야겠습니다....
45: *       *       *       *       *
"""

en_content_1 = """1: CHAPTER 26
2: DR. SEWARD'S DIARY
3: October 29.—I am writing this on the train from Varna to Galatz. Last night, we all gathered a little before sunset. Everyone had completed their tasks to the best of their abilities. As far as our planning, effort, and opportunities allowed, we were fully prepared for the rest of our journey and the work waiting for us in Galatz. When the usual time approached, Mrs. Harker got ready for the hypnosis. Van Helsing had to put in a much longer and more intense effort than usual before she finally slipped into the trance. Usually, she speaks with just a prompt, but this time the Professor had to ask her several firm questions before we learned anything. Finally, she answered:
4: "I can't see anything. We are entirely still. There are no lapping waves, only a steady swirling sound of water softly brushing against the mooring cable. I hear men's voices calling out, both near and far, along with the roll and creak of oars in their locks. A gun goes off somewhere, its echo sounding distant. Footsteps are tramping overhead, and ropes and chains are being dragged. What's this? A sliver of light appears, and I can feel a breeze blowing on me."
5: She stopped there. Moving impulsively, she stood up from the sofa and raised both hands, palms facing up, as if lifting something heavy. Van Helsing and I exchanged a knowing look. Quincey arched his eyebrows and watched her closely, while Harker's hand instinctively gripped the hilt of his Kukri knife. A long silence followed. We all knew her window to speak was closing, but we felt it was pointless to say anything. Suddenly, she sat up straight, opened her eyes, and said sweetly:
6: "Would any of you like a cup of tea? You must all be exhausted!" We wanted to keep her happy, so we agreed. She hurried off to make the tea. Once she was gone, Van Helsing spoke up:
7: "You see, my friends, he is close to land. He has left his earth-filled chest, but he hasn't reached the shore yet. He might hide somewhere during the night, but if he isn't carried ashore or if the ship doesn't dock, he cannot step on land. If it's night, he could change his shape and jump or fly ashore, like he did in Whitby. But if morning comes before he reaches land, he's trapped unless someone carries him. And if someone does carry him, customs officers might discover what's inside the box. Ultimately, if he doesn't escape to the shore tonight or before dawn, he loses an entire day. That means we might arrive in time. If he doesn't escape tonight, we will catch him during the day, trapped in his box and completely at our mercy. He wouldn't dare wake up in his true form for fear of being discovered."
8: There was nothing left to discuss, so we waited patiently until dawn, hoping to learn more from Mrs. Harker then.
9: Early this morning, we waited with bated breath for her answers under hypnosis. It took even longer for her to enter the trance than before. By the time she did, the time left until full sunrise was so short that we started to lose hope. Van Helsing seemed to pour his entire soul into the effort. Finally, responding to his willpower, she replied:
10: "Everything is dark. I hear water lapping right at my level, and the creaking sound of wood rubbing against wood." She paused, and then the red sun rose. We have to wait until tonight.
11: And so we are traveling toward Galatz, consumed by an agonizing wait. We were supposed to arrive between 2:00 and 3:00 a.m., but we are already three hours delayed at Bucharest, meaning we won't get there until well after sunrise. That gives us two more chances for hypnotic messages from Mrs. Harker. Either one could potentially shed more light on what is happening.
12: *       *       *       *       *
13: Later.—Sunset has come and gone. Luckily, it happened during a quiet moment on the train; if we had been stopped at a station, we might not have had the peace and isolation we needed. Mrs. Harker resisted the hypnosis even more than she did this morning. I'm terrified that her ability to read the Count's sensations might fade away exactly when we need it most. It feels like her own imagination is starting to bleed into her visions. Until now, she has only reported the most basic facts during her trances. If this shift continues, it could eventually lead us in the wrong direction. I would be happy if I knew the Count's control over her was fading along with her telepathic connection, but I fear that isn't the case. When she finally spoke, her words were a riddle:
14: "Something is leaving. I can feel it brush past me like a cold breeze. Far away, I hear chaotic noises—men talking in strange languages, the rush of fiercely falling water, and wolves howling." She stopped talking, and a shudder ripped through her body. It grew stronger for a few seconds until she was shaking uncontrollably, as if she were having a seizure. She refused to say another word, even when the Professor sharply demanded answers. When she woke up, she was cold, exhausted, and weak, but her mind was perfectly sharp. She couldn't remember anything and asked us what she had said. After we told her, she sat in total silence for a long time, thinking deeply.
15: *       *       *       *       *
"""

en_content_2 = """16: October 30, 7 a.m.—We are close to Galatz now, and I might not have time to write later. We all anxiously awaited sunrise this morning. Knowing how difficult it was becoming to induce the hypnotic trance, Van Helsing started his hand motions earlier than usual. It had no effect, however, until the exact scheduled time. Even then, she resisted fiercely, only giving in a single minute before the sun peeked over the horizon. The Professor immediately began questioning her, and her reply came just as swiftly:
17: "Everything is dark. I hear water rushing past, level with my ears, and the sound of wood creaking against wood. Cows are mooing in the distance. There is another sound, a strange one like—" She stopped, her face turning pale, and then even paler.
18: "Keep going! Continue! Speak, I command you!" Van Helsing cried out in an agonizing tone. His eyes showed despair because the rising sun was already casting a red glow on Mrs. Harker's pale face. She opened her eyes, and we all flinched as she spoke—sweetly and seemingly without a care in the world:
19: "Oh, Professor, why are you asking me to do something you know I can't? I don't remember a thing." Noticing the shock on our faces, her expression shifted to concern. She looked at us, bewildered, and said:
20: "What did I say? What did I do? I don't know anything, except that I was lying here half-asleep and heard you say, 'Keep going! Speak, I command you!' It felt so strange to hear you ordering me around like I was a naughty child!"
21: "Oh, Madam Mina," he replied sadly, "if you needed proof of how much I love and respect you, this is it. A word spoken purely for your own good, spoken more urgently than ever, seems strange to you because I am ordering someone I am normally so proud to obey!"
22: The train whistles are blowing; we are arriving in Galatz. We are burning with anxiety and eagerness.
23: Mina Harker's Journal.
24: October 30.—Mr. Morris brought me to the hotel rooms we booked by telegram. He was the most logical choice to escort me, since he doesn't speak any foreign languages and could easily be spared. We divided our forces much like we did in Varna. The only difference was that Lord Godalming went to the Vice-Consul. Since we were in a massive rush, we hoped his aristocratic title would act as an immediate guarantee for the officials. Jonathan and the two doctors went to the shipping agent to get the details on the Czarina Catherine's arrival.
25: *       *       *       *       *
26: Later.—Lord Godalming is back. The Consul is out of town, and the Vice-Consul is sick, so a clerk was handling the daily routine. The clerk was very accommodating and offered to do whatever he could to help.
27: Jonathan Harker's Journal.
28: October 30.—At 9:00 a.m., Dr. Van Helsing, Dr. Seward, and I visited Mackenzie & Steinkoff, the local agents for the London-based Hapgood firm. They had already received a telegram from London responding to Lord Godalming's request, instructing them to give us any assistance we needed. They were incredibly kind and polite, immediately taking us aboard the Czarina Catherine, which was anchored out in the river harbor. There, we met the captain, a man named Donelson, who told us about his voyage. He swore he had never seen such favorable sailing conditions in his entire life.
29: "Man!" he exclaimed. "It actually scared us. We kept expecting some terrible stroke of bad luck to hit and even out the average. It's downright unnatural to sail from London to the Black Sea with a wind right behind you the whole way, as if the Devil himself were blowing on the sails for his own reasons. And the entire time, we couldn't see a single thing! Whenever we got near another ship, a port, or a headland, a thick fog would drop down and travel with us. By the time it lifted and we looked around, there wasn't a damn thing in sight. We sailed past Gibraltar without even being able to signal. Until we hit the Dardanelles and had to wait for our passage permit, we never even came within shouting distance of anyone. At first, I wanted to drop the sails and wait for the fog to clear. But then I figured that if the Devil was dead set on pushing us into the Black Sea quickly, he was going to do it whether we liked it or not. A fast voyage wouldn't hurt our reputation with the owners or ruin our cargo. I figured the Old Man, having gotten what he wanted, would be grateful enough that we didn't get in his way." This bizarre mix of simplicity, cunning, superstition, and raw business logic caught Van Helsing's attention. He replied:
30: "My friend, that Devil is much smarter than some give him credit for, and he knows when he has met his match!" The captain seemed rather pleased by the compliment and continued:
31: "Once we passed the Bosphorus, the crew started complaining. A few of the Romanian sailors came up to me and asked me to toss a massive wooden box overboard. A strange-looking old man had loaded it onto the ship just before we left London. I'd noticed the men glaring at him and flashing the two-finger sign to ward off the 'evil eye' when they saw him. I tell you, the superstition of foreigners is absolutely ridiculous! I told them to get back to work immediately. But shortly after, when the fog rolled in on us, I started feeling a little bit like they did. I wouldn't blame it on the big box, though. Anyway, we kept going. Since the fog didn't break for five days, I just let the wind push us. If the Devil wanted to get somewhere, well, he'd get there just fine. If not, we'd keep a sharp lookout anyway. Sure enough, we had a clear path and deep water the entire way. Two days ago, when the morning sun broke through the mist, we found ourselves right in the river across from Galatz. The Romanians lost their minds. They didn't care about right or wrong; they just wanted me to take the box and throw it into the river. I had to argue with them using a heavy wooden spike. By the time the last of them picked himself up off the deck holding his bleeding head, I had convinced them that, 'evil eye' or not, my owners' property and trust were safer in my hands than at the bottom of the Danube. Keep in mind, they had already hauled the box up to the deck to toss it. Since it was marked 'Galatz via Varna,' I figured I'd let it sit there until we unloaded at the port and got rid of it entirely. We didn't do much unloading that day and had to spend the night anchored. But early the next morning, a full hour before sunrise, a man came aboard with a written order from England to pick up a box marked for a Count Dracula. It worked out perfectly since the thing was already sitting on the deck. His paperwork was in order, and I was thrilled to get rid of the damn thing. Honestly, I was starting to feel uneasy about it myself. If the Devil did have luggage on my ship, I'm betting it was that exact box!"
32: "What was the name of the man who took it?" Van Helsing asked, barely containing his excitement.
33: "I'll tell you right now!" the captain answered. He stepped down into his cabin and brought back a receipt signed by "Immanuel Hildesheim." The address listed was 16 Burgen-strasse. We quickly realized this was all the Captain knew, so we thanked him and left.
34: We found Hildesheim in his office. He was a Jewish man who looked like a caricature from an Adelphi Theatre play, complete with a sheep-like nose and a fez. His cooperation required cash—we were forced to punctuate every sentence with coins—but after some haggling, he told us what he knew. The information was simple but critical. He had received a letter from a Mr. de Ville in London, instructing him to receive a box arriving at Galatz on the Czarina Catherine. He was told to pick it up before sunrise, if possible, to bypass customs. Once he had the box, he was to hand it over to a man named Petrof Skinsky, who did business with the Slovak traders running down the river to the port. Hildesheim was paid with an English banknote, which he had already cashed for gold at the Danube International Bank. When Skinsky showed up, Hildesheim took him straight to the ship and handed the box over directly to save on porter fees. That was everything he knew.
35: We immediately started looking for Skinsky, but we couldn't find him. One of his neighbors, who clearly didn't like him very much, said he had left two days ago, and no one knew where he went. His landlord backed up this story, saying a messenger had dropped off Skinsky's house key and his past-due rent—paid in British currency—between 10:00 and 11:00 the previous night. We were at a dead end once again.
36: While we were talking, a man ran up, gasping for breath. He blurted out that Skinsky's body had just been found inside the graveyard wall of St. Peter's church. His throat had been ripped wide open, as if by a wild animal. The people we had been talking to rushed off to see the gruesome sight, with the women screaming, "This is the work of a Slovak!" We hurried away in the opposite direction, terrified of being dragged into the investigation and delayed.
37: We couldn't reach any solid conclusions on the way home. We were all completely convinced that the box was moving somewhere by water, but we still had to figure out where. We returned to the hotel and to Mina with heavy hearts.
38: Once we gathered, the first order of business was deciding whether to bring Mina back into our confidence. Things were getting desperate. It was a risky move, but it gave us a fighting chance. As a first step, I formally released myself from the promise I made to her to keep her in the dark.
39: Mina Harker's Journal.
40: October 30, evening.—The men were so tired, worn out, and depressed that it was useless to try and plan anything until they got some sleep. I asked them all to lie down for half an hour while I typed out everything that had happened up to this point. I am so incredibly grateful to the person who invented the "Traveller's" typewriter, and to Mr. Morris for buying this one for me. I would have been totally lost trying to do all this work with just a pen...
41: The typing is finished. My poor, dear Jonathan—the things he must have suffered, and what he must be suffering right now. He is lying on the sofa, barely looking like he's breathing, his entire body seemingly collapsed. His eyebrows are pulled together, and his face is tight with pain. Poor man, maybe he's dreaming, because his face is all scrunched up as if he is concentrating deeply on something. Oh! If only there was some way I could help... I will do everything I possibly can.
42: I asked Dr. Van Helsing for all the papers and journals I haven't seen yet... While the men are resting, I am going to read through everything very carefully. Maybe I can figure something out. I'm going to try to follow the Professor's example and look at the facts objectively, without any preconceived notions...
43: *       *       *       *       *
44: I truly believe that, by the grace of God, I have found something. I am going to get the maps and look them over...
45: *       *       *       *       *
"""

with open('c:/git_repo/TKprof_book/books/dracula/chapters/ch26_ko_modern.txt', 'w', encoding='utf-8') as f:
    f.write(ko_content_1 + "\\n" + ko_content_2)

with open('c:/git_repo/TKprof_book/books/dracula/chapters/ch26_en_modern.txt', 'w', encoding='utf-8') as f:
    f.write(en_content_1 + "\\n" + en_content_2)
