import json

translations = {
    "H001": {"ko": "[3부 15장: 발자국이 영원히 사라지다]", "en": "[Book 3 Chapter 15: The Footsteps Die Out For Ever]"},
    "P002_1": {"ko": "파리의 거리를 따라 사형수들을 실은 수레가 공허하고 거친 소리를 내며 덜컹거립니다.", "en": "Along the streets of Paris, the carts carrying the condemned rumble with a hollow and harsh sound."},
    "P002_2": {"ko": "여섯 대의 수레가 그날 처형될 사람들을 단두대로 싣고 갑니다.", "en": "Six carts carry the people to be executed that day to the guillotine."},
    "P002_3": {"ko": "상상할 수 있는 모든 탐욕스럽고 만족할 줄 모르는 괴물들이 단두대라는 하나의 실체로 융합되었습니다.", "en": "All the greedy and insatiable monsters one could imagine have been fused into the single reality of the guillotine."},
    "P002_4": {"ko": "그러나 풍요로운 토양과 기후를 가진 프랑스에서도, 이 끔찍한 공포를 만들어낸 조건들보다 더 확실하게 성숙할 수 있는 생명체는 없습니다.", "en": "And yet, even in France with its rich soil and climate, there is no living thing that will grow to maturity more certainly than the conditions that produced this terrible horror."},
    "P002_5": {"ko": "비슷한 억압의 망치 아래에서 인류를 다시 한번 짓누르면, 똑같이 고통받는 형태로 뒤틀릴 것입니다.", "en": "Crush humanity once again under similar hammers of oppression, and it will twist itself into the same tortured forms."},
    "P002_6": {"ko": "탐욕스러운 방종과 억압의 씨앗을 다시 뿌리면, 틀림없이 그 종류에 따라 같은 열매를 맺을 것입니다.", "en": "Sow the seed of greedy indulgence and oppression once more, and it will surely bear the same fruit according to its kind."},
    "P003_1": {"ko": "여섯 대의 수레가 거리를 굴러갑니다.", "en": "Six carts roll along the streets."},
    "P003_2": {"ko": "강력한 마법사인 '시간'이여, 이것들을 예전의 모습으로 되돌려 보십시오. 그러면 절대 군주들의 마차, 봉건 귀족들의 마차, 화려한 악녀들의 치장, 내 아버지의 집이 아니라 도둑들의 소굴인 교회, 굶주리는 수백만 농민들의 오두막이었음을 알게 될 것입니다!", "en": "Oh powerful magician Time, change these back to what they were, and they will be seen as the carriages of absolute monarchs, the carriages of feudal nobles, the outfits of flashy wicked women, the churches that are dens of thieves instead of my father's house, and the huts of millions of starving peasants!"},
    "P003_3": {"ko": "아닙니다.", "en": "No;"},
    "P003_4": {"ko": "창조주가 정하신 질서를 위엄 있게 이행하는 위대한 마법사는 결코 자신의 변형을 되돌리지 않습니다. 지혜로운 아라비아 이야기에서 현자들은 마법에 걸린 자들에게 '신의 뜻에 의해 이 모습으로 변했다면 그대로 머물러라!'라고 말합니다.", "en": "The great magician who majestically carries out the Creator's appointed order never reverses his transformations. In wise Arabian stories, seers say to the enchanted, 'If you are changed into this shape by the will of God, then remain so!"},
    "P003_5": {"ko": "하지만, 단순한 지나가는 마법으로 이 형태를 띠게 된 것이라면, 예전의 모습을 되찾으라!' 변함없고 희망도 없이, 수레들은 굴러갑니다.", "en": "But, if you wear this form through a mere passing spell, then return to your former appearance!' Changeless and hopeless, the carts roll along."},
    "P004_1": {"ko": "여섯 대의 수레의 우울한 바퀴가 돌아가면서, 그들은 거리의 민중들 사이에 길고 구부러진 고랑을 파는 것처럼 보입니다.", "en": "As the gloomy wheels of the six carts turn, they seem to plow a long crooked furrow among the people in the streets."},
    "P004_2": {"ko": "얼굴들의 이랑이 이쪽저쪽으로 던져지고, 쟁기들은 꾸준히 앞으로 나아갑니다.", "en": "Ridges of faces are thrown to this side and that, and the plows go steadily onward."},
    "P004_3": {"ko": "그 집들의 정규 주민들은 이 광경에 너무 익숙해져서, 많은 창문에는 사람이 없고, 어떤 곳에서는 손으로 하던 일을 멈추지도 않은 채 눈으로 수레 안의 얼굴들을 살핍니다.", "en": "The regular inhabitants of the houses are so used to the spectacle that in many windows there are no people, and in some, they don't even stop what their hands are doing while their eyes survey the faces in the carts."},
    "P004_4": {"ko": "여기저기서, 구경거리를 보러 온 방문객을 맞이한 집주인도 있습니다.", "en": "Here and there, an inmate has visitors to see the sight;"},
    "P004_5": {"ko": "그러면 그는 큐레이터나 공인된 해설자 같은 자기만족적인 태도로 이 수레와 저 수레를 손가락으로 가리키며, 어제는 누가 저기 앉았고 그저께는 누가 저기 있었는지 말해주는 듯합니다.", "en": "Then he points his finger, with the self-satisfaction of a curator or authorized guide, to this cart and that, and seems to tell who sat here yesterday and who there the day before."},
    "P005_1": {"ko": "수레에 탄 사람들 중 일부는 무표정한 응시로 이 모든 것들과 그들의 마지막 길가에 있는 모든 것들을 관찰합니다.", "en": "Of the riders in the carts, some observe these things, and all things on their last roadside, with an impassive stare;"},
    "P005_2": {"ko": "다른 사람들은 삶과 사람들의 방식에 대한 미련을 가지고 봅니다.", "en": "Others look with a lingering interest in the ways of life and men."},
    "P005_3": {"ko": "어떤 이들은 고개를 떨군 채 앉아 무언의 절망에 빠져 있습니다.", "en": "Some, seated with drooping heads, are sunk in silent despair;"},
    "P005_4": {"ko": "또 어떤 이들은 자신의 외모에 너무 신경을 쓴 나머지, 극장이나 그림에서 보았음직한 시선을 군중에게 던집니다.", "en": "Again, there are some so mindful of their looks that they cast glances at the crowd like those seen in theaters and pictures."},
    "P005_5": {"ko": "여럿은 눈을 감고 생각하거나, 방황하는 생각들을 모으려 애씁니다.", "en": "Several close their eyes and think, or try to gather their straying thoughts."},
    "P005_6": {"ko": "오직 한 사람, 미친 듯한 표정의 비참한 자만이 공포에 너무 산산조각 나고 취해서 노래하고 춤추려 합니다.", "en": "Only one, a miserable creature with a crazed look, is so shattered and drunk by horror that he sings and tries to dance."},
    "P005_7": {"ko": "그들 중 단 한 명도 표정이나 몸짓으로 사람들의 동정을 구하지 않습니다.", "en": "Not one of the entire number appeals for the pity of the people by look or gesture."},
    "P006_1": {"ko": "수레들과 나란히 말을 타고 가는 다양한 기병들의 호위대가 있으며, 얼굴들이 종종 그들 중 일부를 올려다보며 질문을 던집니다.", "en": "There is a guard of various horsemen riding alongside the carts, and faces are often turned up to them, asking some question."},
    "P006_2": {"ko": "항상 같은 질문인 것 같습니다. 왜냐하면, 그 뒤에는 항상 사람들이 세 번째 수레를 향해 몰려들기 때문입니다.", "en": "It seems to always be the same question, for it is always followed by a crowd of people pressing toward the third cart."},
    "P006_3": {"ko": "그 수레와 나란히 가던 기병들이 자주 칼로 그 안의 한 남자를 가리킵니다.", "en": "The horsemen alongside that cart frequently point out one man in it with their swords."},
    "P006_4": {"ko": "가장 큰 호기심은, 그가 누구인지 아는 것입니다.", "en": "The main curiosity is to know which one he is;"},
    "P006_5": {"ko": "그는 고개를 숙인 채 수레 뒤쪽에 서서, 수레 가장자리에 앉아 그의 손을 잡고 있는 한 어린 소녀와 대화를 나눕니다.", "en": "He stands at the back of the cart with his head bowed down, talking with a mere girl who sits on the side of the cart and holds his hand."},
    "P006_6": {"ko": "그는 주변 상황에 대한 호기심이나 관심이 없으며, 오직 소녀에게만 이야기합니다.", "en": "He has no curiosity or care for the scene around him, and always speaks to the girl."},
    "P006_7": {"ko": "생토노레의 긴 거리 여기저기서 그를 향한 고함 소리가 터져 나옵니다.", "en": "Here and there in the long street of St. Honoré, cries are raised against him."},
    "P006_8": {"ko": "생토노레 거리에서 그를 비난하는 외침이 들립니다.", "en": "Cries of condemnation are heard against him in the street of St. Honoré."},
    "P006_9": {"ko": "그 소리들이 그를 조금이라도 동요시킨다면, 그것은 오직 조용한 미소를 짓게 할 뿐입니다. 그는 머리카락을 조금 더 느슨하게 흔들어 얼굴을 가립니다.", "en": "If they move him at all, it is only to a quiet smile, as he shakes his hair a little more loosely about his face."},
    "P006_10": {"ko": "그는 팔이 묶여 있어서 쉽게 얼굴을 만질 수 없습니다.", "en": "He cannot easily touch his face because his arms are bound."},
    "P007_1": {"ko": "교회 계단에는 수레들이 오기를 기다리며 스파이이자 감옥의 끄나풀이 서 있습니다.", "en": "On the steps of a church, waiting for the carts to come up, stands the Spy and prison informant."},
    "P007_2": {"ko": "그는 첫 번째 수레를 들여다봅니다.", "en": "He looks into the first of them:"},
    "P007_3": {"ko": "거기 없습니다.", "en": "not there."},
    "P007_4": {"ko": "그는 두 번째 수레를 들여다봅니다.", "en": "He looks into the second:"},
    "P007_5": {"ko": "거기 없습니다.", "en": "not there."},
    "P007_6": {"ko": "그는 세 번째 수레를 들여다볼 때 얼굴이 밝아지며, '그가 나를 희생시켰는가?'라고 이미 스스로에게 묻고 있습니다.", "en": "He is already asking himself, 'Has he sacrificed me?' when his face clears as he looks into the third."},
    "P008_1": {"ko": "그의 뒤에 있던 한 남자가 묻습니다. '에브레몽이 누구지?'", "en": "A man behind him says, 'Which is Evrémonde?'"},
    "P009_1": {"ko": "'저기.", "en": "'That one."},
    "P009_2": {"ko": "저 뒤에 있는 사람이오.'", "en": "At the back there.'"},
    "P010_1": {"ko": "'소녀의 손을 잡고 있는 사람?'", "en": "'With his hand in the girl's?'"},
    "P011_1": {"ko": "'그렇소.'", "en": "'Yes.'"},
    "P012_1": {"ko": "남자가 소리칩니다. '타도하라, 에브레몽!", "en": "The man cries, 'Down with Evrémonde!"},
    "P012_2": {"ko": "모든 귀족들을 단두대로!", "en": "To the Guillotine with all aristocrats!"},
    "P012_3": {"ko": "타도하라, 에브레몽!'", "en": "Down with Evrémonde!'"},
    "P013_1": {"ko": "'쉿, 조용히!' 스파이가 조심스럽게 그에게 간청합니다.", "en": "'Hush, hush!' the Spy timidly entreats him."},
    "P014_1": {"ko": "'왜 안 되오, 시민?'", "en": "'And why not, citizen?'"},
    "P015_1": {"ko": "'그는 대가를 치르러 가는 길입니다.", "en": "'He is going to pay the penalty:"},
    "P015_2": {"ko": "5분 안에 치르게 될 거요.", "en": "it will be paid in five more minutes."},
    "P015_3": {"ko": "그를 평안히 내버려 두시오.'", "en": "Let him be at peace.'"},
    "P016_1": {"ko": "하지만 남자가 계속해서 '타도하라, 에브레몽!' 하고 소리치자, 에브레몽의 얼굴이 잠시 그를 향합니다.", "en": "But as the man continues to shout, 'Down with Evrémonde!' the face of Evrémonde is turned toward him for a moment."},
    "P016_2": {"ko": "그러자 에브레몽은 스파이를 보고 유심히 쳐다본 후, 제 갈 길을 갑니다.", "en": "Evrémonde then sees the Spy, looks attentively at him, and goes his way."},
    "P017_1": {"ko": "시계가 세 시를 치고 있고, 군중들 사이에 파인 고랑이 돌아서 처형장으로 향하며 끝나려 합니다.", "en": "The clocks are striking three, and the furrow plowed among the crowd is turning around to enter the place of execution and end."},
    "P017_2": {"ko": "모두가 단두대를 향해 따라가고 있기 때문에, 이쪽저쪽으로 던져졌던 이랑들은 이제 마지막 쟁기가 지나가자 부서지며 그 뒤를 덮습니다.", "en": "The ridges thrown to this side and that now crumble in and close behind the last plow as it passes on, for all are following to the Guillotine."},
    "P017_3": {"ko": "그 앞에는 마치 대중 오락을 위한 정원처럼 의자에 앉아 여러 여성들이 바쁘게 뜨개질을 하고 있습니다.", "en": "In front of it, seated in chairs as if in a public diversion garden, are a number of women busily knitting."},
    "P017_4": {"ko": "가장 앞쪽 의자들 중 하나에 복수의 여신(The Vengeance)이 서서 그녀의 친구를 찾고 있습니다.", "en": "On one of the foremost chairs stands The Vengeance, looking around for her friend."},
    "P018_1": {"ko": "'테레즈!' 그녀가 날카로운 목소리로 소리칩니다. '그녀를 본 사람 없어?", "en": "'Thérèse!' she cries in her shrill tones. 'Who has seen her?"},
    "P018_2": {"ko": "테레즈 드파르지!'", "en": "Thérèse Defarge!'"},
    "P019_1": {"ko": "'그녀는 전에는 한 번도 빠진 적이 없는데,' 자매단의 한 뜨개질하는 여성이 말합니다.", "en": "'She never missed before,' says a knitting-woman of the sisterhood."},
    "P020_1": {"ko": "'아니야.", "en": "'No;"},
    "P020_2": {"ko": "지금도 빠지지 않을 거야,' 복수의 여신이 짜증스럽게 소리칩니다. '테레즈.'", "en": "nor will she miss now,' cries The Vengeance petulantly. 'Thérèse.'"},
    "P021_1": {"ko": "'더 크게 불러봐,' 여성이 권합니다.", "en": "'Louder,' the woman recommends."},
    "P022_1": {"ko": "아!", "en": "Ah!"},
    "P022_2": {"ko": "더 크게, 복수의 여신아, 훨씬 더 크게 불러봐. 그래도 그녀는 네 목소리를 거의 듣지 못할 거야.", "en": "Louder, Vengeance, much louder, and still she will barely hear you."},
    "P022_3": {"ko": "더 크게, 복수의 여신아, 약간의 욕설이라도 섞어서 불러봐. 그래도 그녀를 데려오기는 어려울 거야.", "en": "Louder yet, Vengeance, with a little oath or two added, and yet it will hardly bring her."},
    "P022_4": {"ko": "다른 여자들을 위아래로 보내 어딘가에 머뭇거리고 있을 그녀를 찾게 해봐.", "en": "Send other women up and down to look for her, lingering somewhere;"},
    "P022_5": {"ko": "하지만, 그 심부름꾼들이 끔찍한 일들을 저질렀을지라도, 그들 스스로 그녀를 찾을 만큼 멀리까지 갈지는 의문이야!", "en": "and yet, even though the messengers have done dreadful deeds, it is questionable whether they will willingly go far enough to find her!"},
    "P023_1": {"ko": "'운도 지지리 없지!' 복수의 여신이 의자에서 발을 구르며 소리칩니다. '수레들이 왔잖아!", "en": "'Bad Luck!' cries The Vengeance, stamping her foot on the chair, 'and here are the carts!"},
    "P023_2": {"ko": "에브레몽은 눈 깜짝할 사이에 처형될 텐데, 그녀가 여기 없다니!", "en": "And Evrémonde will be dispatched in a wink, and she is not here!"},
    "P023_3": {"ko": "내 손에 있는 그녀의 뜨개질과 그녀를 위해 준비된 빈 의자를 봐.", "en": "See her knitting in my hand, and her empty chair ready for her."},
    "P023_4": {"ko": "화가 나고 실망스러워서 울고 싶어!'", "en": "I cry with vexation and disappointment!'"},
    "P024_1": {"ko": "복수의 여신이 높은 곳에서 내려와 그 일을 하려고 할 때, 수레들이 사람들을 내려놓기 시작합니다.", "en": "As The Vengeance descends from her high spot to do it, the carts begin to discharge their loads."},
    "P024_2": {"ko": "성 단두대(Sainte Guillotine)의 집행관들은 가운을 입고 준비를 마쳤습니다.", "en": "The ministers of Holy Guillotine are robed and ready."},
    "P024_3": {"ko": "쾅! -- 머리 하나가 높이 들리고, 조금 전만 해도 그 머리가 생각하고 말할 수 있었을 때는 쳐다보지도 않던 뜨개질하는 여성들이 '하나'를 셉니다.", "en": "Crash!--A head is held up, and the knitting-women, who barely lifted their eyes to look at it a moment ago when it could think and speak, count One."},
    "P025_1": {"ko": "두 번째 수레가 비워지고 앞으로 나아갑니다.", "en": "The second cart empties and moves on;"},
    "P025_2": {"ko": "세 번째 수레가 다가옵니다.", "en": "the third comes up."},
    "P025_3": {"ko": "쾅! -- 그리고 뜨개질하는 여성들은 하던 일을 멈추거나 주저하지 않고 '둘'을 셉니다.", "en": "Crash!--And the knitting-women, never faltering or pausing in their work, count Two."},
    "P026_1": {"ko": "에브레몽으로 추정되는 자가 내려오고, 재봉사 아가씨가 그의 뒤를 이어 들어올려집니다.", "en": "The supposed Evrémonde descends, and the seamstress is lifted out right after him."},
    "P026_2": {"ko": "그는 내릴 때 그녀의 인내심 많은 손을 놓지 않고, 약속한 대로 여전히 잡고 있습니다.", "en": "He has not let go of her patient hand while getting out, but still holds it as he promised."},
    "P026_3": {"ko": "그는 끊임없이 윙윙거리며 오르내리는 무시무시한 기계를 등지도록 그녀를 조심스럽게 내려놓고, 그녀는 그의 얼굴을 보며 감사를 표합니다.", "en": "He gently places her with her back to the crashing machine that constantly whirs up and falls, and she looks into his face and thanks him."},
    "P027_1": {"ko": "'친절한 낯선 분, 당신이 아니었다면 저는 이렇게 침착하지 못했을 거예요. 저는 본래 심약하고 가엾은 작은 존재니까요.", "en": "'If it weren't for you, dear stranger, I wouldn't be so composed, for I am naturally a poor little thing, faint of heart;"},
    "P027_2": {"ko": "또한 우리가 오늘 이곳에서 희망과 위안을 얻을 수 있도록 처형당하신 그분(예수님)께 제 생각을 모으지도 못했을 거예요.", "en": "nor would I have been able to raise my thoughts to Him who was put to death so that we might have hope and comfort here today."},
    "P027_3": {"ko": "하늘이 저에게 당신을 보내주신 것 같아요.'", "en": "I think you were sent to me by Heaven.'"},
    "P028_1": {"ko": "'아니면 당신을 나에게 보내셨거나요,' 시드니 칼튼이 말합니다. '내 눈을 똑바로 봐요, 사랑하는 아이여. 다른 건 신경 쓰지 말고요.'", "en": "'Or you to me,' says Sydney Carton. 'Keep your eyes on me, dear child, and don't mind any other object.'"},
    "P029_1": {"ko": "'당신 손을 잡고 있는 동안엔 아무것도 신경 쓰지 않아요.", "en": "'I mind nothing while I hold your hand."},
    "P029_2": {"ko": "손을 놓을 때도 그들이 빨리 끝내준다면 아무것도 신경 쓰지 않을 거예요.'", "en": "I will mind nothing when I let it go, if they are quick.'"},
    "P030_1": {"ko": "'그들은 빠를 거예요.", "en": "'They will be rapid."},
    "P030_2": {"ko": "두려워 말아요!'", "en": "Fear not!'"},
    "P031_1": {"ko": "두 사람은 빠르게 줄어드는 희생자들의 무리 속에 서 있지만, 마치 둘만 있는 것처럼 이야기합니다.", "en": "The two stand in the fast-thinning crowd of victims, but they speak as if they were alone."},
    "P031_2": {"ko": "눈과 눈, 목소리와 목소리, 손과 손, 마음과 마음을 맞대고, 너무나 멀리 떨어져 있고 달랐던 만물 어머니의 이 두 자녀는 어두운 길에서 만나 함께 집으로 돌아가 그녀의 품에서 쉬려 합니다.", "en": "Eye to eye, voice to voice, hand to hand, heart to heart, these two children of the Universal Mother, otherwise so wide apart and different, have come together on the dark highway to go home together and rest in her bosom."},
    "P032_1": {"ko": "'용감하고 관대한 친구여, 마지막으로 질문 하나만 해도 될까요?", "en": "'Brave and generous friend, will you let me ask you one last question?"},
    "P032_2": {"ko": "저는 아는 게 별로 없어서, 그게 아주 조금 걱정이 되네요.'", "en": "I am very ignorant, and it troubles me--just a little.'"},
    "P033_1": {"ko": "'뭔지 말해봐요.'", "en": "'Tell me what it is.'"},
    "P034_1": {"ko": "'저에게는 저처럼 고아인 하나뿐인 친척 사촌이 있는데, 제가 아주 많이 사랑해요.", "en": "'I have a cousin, an only relative and an orphan like myself, whom I love very dearly."},
    "P034_2": {"ko": "저보다 다섯 살 어리고, 남쪽 지방의 농가에 살고 있어요.", "en": "She is five years younger than I, and she lives in a farmer's house in the south country."},
    "P034_3": {"ko": "가난이 우리를 갈라놓았고, 그녀는 내 운명에 대해 아무것도 몰라요. 저는 글을 쓸 줄 모르거든요. 설령 쓸 줄 안다 해도 어떻게 그녀에게 이 사실을 말하겠어요!", "en": "Poverty separated us, and she knows nothing of my fate--for I cannot write--and even if I could, how could I tell her!"},
    "P034_4": {"ko": "차라리 이대로가 나아요.'", "en": "It is better as it is.'"},
    "P035_1": {"ko": "'그래요, 맞아요.", "en": "'Yes, yes:"},
    "P035_2": {"ko": "이대로가 낫소.'", "en": "better as it is.'"},
    "P036_1": {"ko": "'우리가 오는 동안 계속 생각했던 것, 그리고 나에게 큰 힘이 되어주는 당신의 친절하고 강인한 얼굴을 보며 지금도 생각하는 건 이거예요. 공화국이 정말 가난한 사람들에게 좋은 일을 하고, 그들이 덜 배고프고 모든 면에서 덜 고통받게 된다면, 그녀는 오래 살지도 몰라요.", "en": "'What I have been thinking as we came along, and what I am still thinking now as I look into your kind, strong face which gives me so much support, is this:--If the Republic really does good to the poor, and they become less hungry and suffer less in all ways, she may live a long time:"},
    "P036_2": {"ko": "어쩌면 늙을 때까지 살지도 몰라요.'", "en": "she may even live to be old.'"},
    "P037_1": {"ko": "'그러면 어떻게 되나요, 다정한 자매여?'", "en": "'What then, my gentle sister?'"},
    "P038_1": {"ko": "'당신 생각은 어때요?' 그토록 많은 인내심을 담고 있던 불평 없는 눈에 눈물이 고이고, 입술이 조금 더 벌어지며 떨립니다.", "en": "'Do you think:' the uncomplaining eyes that hold so much endurance fill with tears, and the lips part a little more and tremble:"},
    "P038_2": {"ko": "'내가 당신과 나 둘 다 자비롭게 보호받을 그 더 나은 세상에서 그녀를 기다리는 동안, 나에게는 그 시간이 길게 느껴질까요?'", "en": "'that it will seem long to me, while I wait for her in the better land where I trust both you and I will be mercifully sheltered?'"},
    "P039_1": {"ko": "'그럴 리 없소, 나의 아이여.", "en": "'It cannot be, my child;"},
    "P039_2": {"ko": "그곳에는 시간도 없고, 고통도 없으니까요.'", "en": "there is no Time there, and no trouble there.'"},
    "P040_1": {"ko": "'당신은 제게 정말 큰 위로가 되네요!", "en": "'You comfort me so much!"},
    "P040_2": {"ko": "저는 너무 무지해요.", "en": "I am so ignorant."},
    "P040_3": {"ko": "이제 당신에게 키스해도 될까요?", "en": "Am I to kiss you now?"},
    "P040_4": {"ko": "때가 왔나요?'", "en": "Is the moment come?'"},
    "P041_1": {"ko": "'그렇소.'", "en": "'Yes.'"},
    "P042_1": {"ko": "그녀가 그의 입술에 입 맞추고,", "en": "She kisses his lips;"},
    "P042_2": {"ko": "그는 그녀에게 입 맞춥니다.", "en": "he kisses hers;"},
    "P042_3": {"ko": "그들은 엄숙하게 서로를 축복합니다.", "en": "they solemnly bless each other."},
    "P042_4": {"ko": "그가 빈손을 놓아줄 때 그 손은 떨리지 않습니다.", "en": "The free hand does not tremble as he releases it;"},
    "P042_5": {"ko": "그 인내심 많은 얼굴에는 다정하고 밝은 한결같음 외에는 아무것도 없습니다.", "en": "nothing worse than a sweet, bright constancy is on the patient face."},
    "P042_6": {"ko": "그녀는 그다음으로 그보다 앞서 갑니다--그렇게 가버립니다.", "en": "She goes next before him--is gone;"},
    "P042_7": {"ko": "뜨개질하는 여성들이 '스물둘'을 셉니다.", "en": "the knitting-women count Twenty-Two."},
    "P043_1": {"ko": "'나는 부활이요 생명이니, 주께서 말씀하시기를:", "en": "'I am the Resurrection and the Life, says the Lord:"},
    "P043_2": {"ko": "나를 믿는 자는 죽어도 살겠고,", "en": "he who believes in me, even if he dies, will live:"},
    "P043_3": {"ko": "무릇 살아서 나를 믿는 자는 영원히 죽지 아니하리라.'", "en": "and whoever lives and believes in me shall never die.'"},
    "P044_1": {"ko": "수많은 목소리의 웅얼거림, 올려다보는 수많은 얼굴들, 군중의 변두리에서 밀려드는 수많은 발소리로 인해 마치 커다란 물결처럼 한 덩어리가 되어 앞으로 솟구치던 모든 것이 한순간에 사라집니다.", "en": "The murmuring of many voices, the upturning of many faces, the pressing on of many footsteps on the edges of the crowd, so that it swells forward in a mass like one great wave of water, all flashes away."},
    "P044_2": {"ko": "스물셋.", "en": "Twenty-Three."},
    "P045_1": {"ko": "*****", "en": "*****"},
    "P046_1": {"ko": "그날 밤 도시 곳곳에서 사람들은 그에 대해 말했습니다. 그곳에서 본 얼굴 중 가장 평화로운 남자의 얼굴이었다고.", "en": "They said about him around the city that night, that it was the most peaceful man's face ever seen there."},
    "P046_2": {"ko": "많은 이들이 그가 숭고하고 예언자처럼 보였다고 덧붙였습니다.", "en": "Many added that he looked sublime and prophetic."},
    "P047_1": {"ko": "같은 도끼에 의해 희생된 가장 놀라운 사람 중 하나인 어떤 여성은 얼마 전 같은 단두대 아래에서 자신에게 영감을 주는 생각들을 글로 남길 수 있게 해달라고 요청했습니다.", "en": "One of the most remarkable sufferers from the same ax--a woman--had asked at the foot of the same scaffold not long before to be allowed to write down the thoughts that were inspiring her."},
    "P047_2": {"ko": "만약 그가 자신의 생각을 입 밖으로 냈고, 그것이 예언적이었다면, 아마 이러했을 것입니다.", "en": "If he had spoken his thoughts aloud, and they were prophetic, they would have been these:"},
    "P048_1": {"ko": "'나는 바사드, 클라이, 드파르지, 복수의 여신, 배심원, 판사 등, 낡은 것들의 파괴 위에서 일어난 새로운 압제자들의 긴 대열이 이 보복의 도구가 현재의 쓰임새를 다하기 전에 그것에 의해 멸망하는 것을 봅니다.", "en": "'I see Barsad, and Cly, Defarge, The Vengeance, the Juryman, the Judge, and long ranks of the new oppressors who have risen on the destruction of the old, perishing by this instrument of retribution before it ceases its current use."},
    "P048_2": {"ko": "나는 이 심연에서 아름다운 도시와 눈부신 사람들이 일어나는 것을 봅니다. 그리고 앞으로 오랫동안 그들이 진정으로 자유로워지기 위한 투쟁 속에서, 그들의 승리와 패배 속에서, 자연스럽게 태어난 이 시대와 이전 시대의 악이 점차 스스로 속죄하고 소멸해 가는 것을 봅니다.", "en": "I see a beautiful city and a brilliant people rising from this abyss, and in their struggles to be truly free, in their triumphs and defeats over many years to come, I see the evil of this time and the previous time from which it naturally came, gradually paying for itself and wearing out."},
    "P049_1": {"ko": "'내가 내 목숨을 바쳐 지킨 생명들이, 내가 다시는 보지 못할 저 영국에서 평화롭고, 유용하며, 번영하고, 행복하게 살아가는 것을 봅니다.", "en": "'I see the lives for which I laid down my life, peaceful, useful, prosperous, and happy, in that England which I will see no more."},
    "P049_2": {"ko": "나는 그녀가 내 이름을 가진 아이를 품에 안고 있는 것을 봅니다.", "en": "I see her with a child on her bosom, who bears my name."},
    "P049_3": {"ko": "나는 그녀의 아버지가 나이는 들고 허리는 굽었지만, 다른 면에서는 회복되어 치유자로서의 임무에 충실하며 평안히 지내는 것을 봅니다.", "en": "I see her father, aged and bent, but otherwise restored, faithful to all people in his healing job, and at peace."},
    "P049_4": {"ko": "오랫동안 그들의 친구였던 그 좋은 노인이 10년 후 자신이 가진 모든 것으로 그들을 풍요롭게 하고, 평온하게 자신의 보상을 받으러 떠나는 것을 봅니다.", "en": "I see the good old man, their friend for so long, enriching them with all he has in ten years' time, and passing peacefully to his reward."},
    "P050_1": {"ko": "'나는 그들의 마음속에, 그리고 앞으로 세대를 거쳐 그들 후손들의 마음속에 내가 쉴 안식처를 간직하고 있음을 봅니다.", "en": "'I see that I hold a sanctuary in their hearts, and in the hearts of their descendants, generations from now."},
    "P050_2": {"ko": "나는 할머니가 된 그녀가 이 날의 기념일에 나를 위해 우는 것을 봅니다.", "en": "I see her as an old woman, weeping for me on the anniversary of this day."},
    "P050_3": {"ko": "나는 그녀와 그녀의 남편이 일생을 마치고 마지막 지상의 침대에 나란히 누워 있는 것을 봅니다. 그리고 그들 각자가 서로의 영혼 속에서 존경받고 신성하게 여겨진 것 이상으로, 내가 그들 두 사람의 영혼 속에서 존중받고 있음을 압니다.", "en": "I see her and her husband, their lives done, lying side by side in their last earthly bed, and I know that neither was more honored and held sacred in the other's soul than I was in the souls of both."},
    "P051_1": {"ko": "'나는 그녀의 품에 안겨 내 이름을 가졌던 그 아이가 한때 내 것이었던 그 인생길을 스스로 개척해 나가는 것을 봅니다.", "en": "'I see that child who lay on her bosom and bore my name, a man making his way up in that path of life which was once mine."},
    "P051_2": {"ko": "그가 그 길을 아주 훌륭하게 개척하여, 그의 빛으로 인해 내 이름이 그곳에서 영광스럽게 되는 것을 봅니다.", "en": "I see him winning it so well that my name is made glorious there by the light of his."},
    "P051_3": {"ko": "내가 내 이름에 남겼던 오점들이 희미하게 사라지는 것을 봅니다.", "en": "I see the stains I cast upon it faded away."},
    "P051_4": {"ko": "나는 그가 가장 공정한 판사이자 존경받는 남자가 되어, 내가 아는 이마와 금발 머리를 가진 내 이름의 소년과 함께 이곳으로 오는 것을 봅니다--그때는 보기 좋게 변해서 오늘날의 흉측한 흔적은 하나도 남지 않은 이곳으로--그리고 나는 그가 부드럽고 떨리는 목소리로 그 아이에게 내 이야기를 들려주는 것을 듣습니다.", "en": "I see him, foremost of just judges and honored men, bringing a boy of my name, with a forehead I recognize and golden hair, to this place--then a fair place to look at, without a trace of today's ugliness--and I hear him tell the child my story with a tender and faltering voice."},
    "P052_1": {"ko": "'내가 하는 이 일은, 내가 지금까지 했던 어떤 일보다 훨씬, 훨씬 더 훌륭한 일입니다.", "en": "'It is a far, far better thing that I do than I have ever done;"},
    "P052_2": {"ko": "내가 가는 이 안식은, 내가 지금까지 알았던 어떤 안식보다 훨씬, 훨씬 더 훌륭한 안식입니다.'", "en": "it is a far, far better rest that I go to than I have ever known.'"}
}

def translate():
    with open('c:/git_repo/TKprof_book/books/two_cities/json/book3_ch_15.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    for item in data:
        tag = item['tag']
        if tag in translations:
            item['ko'] = translations[tag]['ko']
            item['en'] = translations[tag]['en']
            
    with open('c:/git_repo/TKprof_book/books/two_cities/json/book3_ch_15.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

if __name__ == '__main__':
    translate()
